FCP-INDI/C-PAC

CPAC/generate_motion_statistics/generate_motion_statistics.py

Power motion parameters are calculated from the movement vector as provided by 3dvolreg: "roll pitch yaw dS  dL  dP". There's currently a mistake in the code as the first three numbers are taken to be translations and the last three rotations, even though it should be the other way around.

Power motion parameters calculation fix

---

CPAC/nuisance/nuisance.py

the argument names in 'calc_residuals' function is written differently in the docstring of the function

calc_residuals arguments

---

CPAC/generate_motion_statistics/generate_motion_statistics.py

The list of indices of frames to scrub (output of set_frames_ex) sometimes contains frames that are beyond the end of the scan.
For example, let's say that the scan contains 100 frames (numbered 0, 1, ..., 99) and the framewise displacement of the last frame is above a given threshold. If we scrub also the 2 following frames, the list of frames to scrub contains frames 99, 100, and 101. Frames 100 and 101 are beyond the end of the scan and shouldn't be included in the list.

Fix set_frames_ex to exclude only existing frames

---

CPAC/nuisance/nuisance.py

to prevent
visible deprecation warning:using a non-integer number instead of an integer will result in an error in the future

input integer value in np.zeroes

---

CPAC/pipeline/cpac_pipeline.py

logging to file uses file locking to avoid corrupting the logs, not all systems work with file locking, some have it disabled, somethings like NFS4 don't work with file locking.

added flag to disable log to file

---

CPAC/pipeline/cpac_pipeline.py

`networkx` now uses a stratified API for drawing to allow using different rendering libs.
This minor PR update our use of this new API. It intends to fix #641 .

Update of networkx drawing API

---

scripts/cpac_install.sh

- Pin nipype, wxpython and prov versions
- Install ANTS from apt repository when on ubuntu 16.04

Setup Fixes: packages versions and ANTS setup

---

Singularity

In order to avoid env collisions w the host*, we empty the FREESURFER_HOME var so Nipype will not complain about license/build files.
* Singularity has different configs, and sometimes it will always forward the host environment to the container.

[FIX] Force empty Freesurfer var

---

CPAC/qc/utils.py

Use set_prop_cycle instead of set_color_cycle to fix the following
MatplotlibDeprecationWarning:
/usr/local/miniconda/lib/python2.7/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
warnings.warn(message, mplDeprecation, stacklevel=1)

Use set_prop_cycle instead of deprecated set_color_cycle

---

CPAC/qc/utils.py

```
/usr/local/miniconda/lib/python2.7/site-packages/matplotlib/cbook.py:136: MatplotlibDeprecationWarning: The set_color_cycle attribute was deprecated in version 1.5. Use set_prop_cycle instead.
warnings.warn(message, mplDeprecation, stacklevel=1)
```

[Chore] Fix API update warning

---

CPAC/nuisance/tests/test_nuisance_representations.py
CPAC/nuisance/utils/__init__.py
CPAC/pipeline/cpac_pipeline.py

While trying to troubleshoot an issue with nuisance regressors, I found that some unit tests were failing, so I fixed them, and performed some cleanup of the NuisanceRegressor class by removing an unused argument to the constructor, cleaning up imports, and using `OrderedDict` to retain dictionary key insertion order.

Fix test nuisance representations

---

CPAC/image_utils/spatial_smoothing.py
CPAC/vmhc/__init__.py
CPAC/vmhc/utils.py
CPAC/vmhc/vmhc.py

Update comments relating sigma and FWHM, then remove unused `set_gauss` function. Should resolve #1100 .

Issue 1100 Note about smoothing in vmhc.py

---

.circleci/config.yml
dev/docker_data/run.py

From issues https://github.com/FCP-INDI/C-PAC/issues/1020 and https://github.com/FCP-INDI/C-PAC/issues/1062, there is confusion about the default working directory. These changes make `/tmp` the default working directory, so crash logs, log files, pipeline config and data config files are written there, update the CircleCI configuration to use /tmp as the working directory, and fix some help output from run.py.
The accompanying documentation changes are in https://github.com/FCP-INDI/fcp-indi.github.com/pull/172.

Use /tmp as default working directory consistently

---

README.md
dev/docker_data/run.py

I noticed the [`run --help` description of `--bids_validator_config`](
https://shnizzedy.github.io/fcp-indi.github.com/docs/user/quick.html?highlight=https://github.com/INCF/bids-validator) includes a deprecated link to https://github.com/INCF/bids-validator. This PR
- updates https://github.com/INCF/bids-validator to https://github.com/bids-standard/bids-validator
- updates the dead "hosted on OpenNeuro" (![dead image](http://bids.neuroimaging.io/openneuro_badge.svg)) in the README to one hosted in https://github.com/bids-standard/bids-website (![live image](https://raw.githubusercontent.com/bids-standard/bids-website/gh-pages/old_website/openneuro_badge.svg?sanitize=true))
- updates the alt text for that image from "DOI" to "OpenNeuro"

🔗 BIDs validator links

---

CPAC/resources/configs/pipeline_config_fmriprep-options.yml

ants registration para match to fmriprep-option. 
still missing two para. 
-x, --masks [fixedImageMask,movingImageMask] 
Image masks to limit voxels considered by the metric. Two options are allowed  
for mask specification: 1) Either the user specifies a single mask to be used  
for all stages or 2) the user specifies a mask for each stage. With the latter  
one can select to which stages masks are applied by supplying valid file names.  
If the file does not exist, a mask will not be used for that stage. Note that we  
handle the fixed and moving masks separately to enforce this constraint.  
--float  
Use 'float' instead of 'double' for computations.  
<VALUES>: 0

update ANTs para of fmriprep option config

---

CPAC/nuisance/utils/compcor.py

Disable the computation of square U and Vh, so it does not give memory errors.

[BUGFIX] Memory problems with CompCor

---

CPAC/nuisance/utils/__init__.py

AFNI expects TSVs to have a header row, so the first value was being considered the header. This PR adds a header row to `censors.tsv` and should resolve the issue.
> -----------
>  TSV files: [Sep 2018]
> -----------
> * 1dcat can now also read .tsv files, which are columns of values separated
>   by tab characters (tsv = tab separated values). The first row of a .tsv 
>   file is a set of column labels. After the header row, each column is either
>   all numbers, or is a column of strings. For example
>      Col 1 Col 2 Col 3
>      3.2 7.2 Elvis
>      8.2 -1.2 Sinatra
>      6.66  33.3 20892
>   In this example, the column labels contain spaces, which are NOT separators;
>   the only column separator used in a .tsv file is the tab character.
>   The first and second columns are …

🚑 Fix number of lines in censors.tsv

---

CPAC/pipeline/cpac_pipeline.py
CPAC/utils/strategy.py

Key changes:
- Introduction of a "get" object method for Strategy- unlike __getitem__, it will run a dict.get(). This should only be used for checking strategy info, which may not be initialized yet in the pipeline. The usual __getitem__ approach for everything else.
- Replacing the `etc. in nodes:` checks with `strat.get('registration_method') == etc.`

Proposal of simple format for strategy info within resource pool.

---

CPAC/func_preproc/func_preproc.py

update resource pool for the case 'motion_params' not in strat.
- 'bold_masking_method', 'motion_correction_method', 'motion_correction_ref'.  
current develop is generating Node`gen_motion_stats_None_None_None_0` in [ line ](https://github.com/FCP-INDI/C-PAC/blob/develop/CPAC/pipeline/cpac_pipeline.py#L2214) and making motion relevant crashes when set `runMotionStatisticsFirst : [0]`

update motion strat resource pool

---

CPAC/utils/interfaces/datasink.py

Resolves recurring crashfile
```Python
File "/code/CPAC/utils/interfaces/datasink.py", line 545, in _list_outputs
for src in ensure_list(files):
TypeError: 'NoneType' object is not iterable
```
by setting `files` to an empty list if `files` is `None`.

✏️ Fix minor but frequent sinker TypeError

---

CPAC/pipeline/cpac_pipeline.py

**What It Does, and Where**
Injects user-provided custom tissue masks (from the data config) into the resource pool at the beginning of the pipeline, bypassing tissue segmentation.
**Why**
Allows people to use tissue masks derived by tools not available in C-PAC, or created manually or modified.
**Flowchart**
N/A
**Test Cases**

Allow ingress of tissue masks

---

CPAC/utils/utils.py

```Python
if c.numCoresPerSubject:
{do stuff}
else:
num_cores_per_sub = num_cores/c.numCoresPerSubject
```
has persisted through variable name changes since its introduction in 5103492. That `else` will always fail because it will only be reached if the denominator is falsy.

✏️ If maxCoresPerParticipant unset, set num_cores_per_sub without dividing by maxCoresPerParticipant

---

CPAC/nuisance/__init__.py
CPAC/nuisance/nuisance.py
CPAC/nuisance/tests/test_nuisance.py
CPAC/nuisance/utils/__init__.py

`create_nuisance_workflow` was split into `create_regressor_workflow`, `create_nuisance_regression_workflow` and `filtering_bold_and_regressors` in b3f027e. This PR updates the remaining places `create_nuisance_workflow` was imported to import `create_nuisance_regression_workflow` instead.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created …
```

🚜 `create_nuisance_workflow` → `create_nuisance_regression_workflow`

---

dev/docker_data/required_afni_pkgs.txt

To resolve / prevent
```
OSError: No command "3dCM" found on host < SHA >. Please check that the corresponding package is installed.
```
The package is used in 3 places:
https://github.com/FCP-INDI/C-PAC/blob/6ea89f8665c703a37bf7b87c91439baa3a849594/CPAC/longitudinal_pipeline/longitudinal_workflow.py#L712
https://github.com/FCP-INDI/C-PAC/blob/6ea89f8665c703a37bf7b87c91439baa3a849594/CPAC/func_preproc/func_preproc.py#L825
https://github.com/FCP-INDI/C-PAC/blob/6ea89f8665c703a37bf7b87c91439baa3a849594/CPAC/anat_preproc/anat_preproc.py#L157

➕ Add 3dCM to required AFNI packages

---

CPAC/utils/interfaces/datasink.py
Singularity

Builds on #1313 by @shnizzedy
Fixes #1260 by @HechengJin0 
`CPAC.utils.interfaces.datasink.DataSink._list_outputs` uses `nipype.utils.filemanip.copyfile` which in turn uses [`shutil.copyfile`](https://docs.python.org/3/library/shutil.html#shutil.copyfile):
> If src and dst specify the same file, [SameFileError](https://docs.python.org/3/library/shutil.html#shutil.SameFileError) is raised.
#1313 resolves for matching paths. This PR resolves for matching contents.
index.md`).
Also includes c9fd9ad to resolve a merge error from #1311
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

🚑 Fix SameFileError

---

CPAC/timeseries/timeseries_analysis.py

Fixes #1327 by @shnizzedy
Related to #770 by @sgiavasis, #1265 by @HechengJin0 & #1268 by @shnizzedy
Checks the header row for a leading `#` and drops that character if it exists. Keeps
```CSV
#File,Sub-brick
```
as-is in the first line, so the comments + header changes from
```CSV
#File,Sub-brick
#Mean_1  ,Mean_2  ,Mean_3  ,Mean_4  ,Mean_5  ,Mean_6  ,Mean_7  ,Mean_8  ,Mean_9  ,Mean_10  ,Mean_11  ,Mean_12  ,Mean_13  ,Mean_14  ,Mean_15  ,Mean_16  ,Mean_17  ,Mean_18  ,Mean_19  ,Mean_21  ,Mean_22  ,Mean_23  ,Mean_24  ,Mean_25  ,Mean_26  ,Mean_27  ,Mean_28  ,Mean_29  ,Mean_30  ,Mean_31  ,Mean_32  ,Mean_33  ,Mean_34  ,Mean_35  ,Mean_36  ,Mean_37  ,Mean_38  ,Mean_39  ,Mean_40  ,Mean_41  ,Mean_42  ,Mean_43  ,Mean_44  ,Mean_45  ,Mean_46  ,Mean_47  ,Mean_48  ,Mean_49  ,Mean_50  ,Mean_51  ,Mean_52 …
```

🚑 Fix CSV has x-1 time points, but dataset has x values

---

CPAC/sca/utils.py

Fixes #1357 by @sgiavasis 
This resolves the temporal_regression crashes caused when certain extracted time series CSVs are parsed by this line:
https://github.com/FCP-INDI/C-PAC/blob/5d712c678278985844be27c372047a15733e3c94/CPAC/sca/utils.py#L134
Pandas has been introduced to more cleanly manage the extracted time series CSVs.
Just make sure a full pipeline run with multiple regression enabled doesn't result in  `temporal_regression_sca_0.split_raw_volumes` crash files.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```

More robust ROI label parsing for multiple regression.

---

CPAC/distortion_correction/distortion_correction.py

Fixes https://github.com/FCP-INDI/C-PAC/pull/1400#discussion_r523270119 by @shnizzedy
Related to #1366 by @sgiavasis
Indents https://github.com/FCP-INDI/C-PAC/blob/6fb4ac207f80df5e9a107fa56087d3919b221591/CPAC/distortion_correction/distortion_correction.py#L551-L563 one level to include in loop https://github.com/FCP-INDI/C-PAC/blob/6fb4ac207f80df5e9a107fa56087d3919b221591/CPAC/distortion_correction/distortion_correction.py#L494
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but changing it is …
```

🐛 Fix indentation of code block

---

CPAC/pipeline/schema.py
dev/docker_data/default_pipeline.yml

Fixes #1425 by @shnizzedy
* Updates, attempts to clarify, the comments in the default pipeline config based on https://github.com/FCP-INDI/C-PAC/discussions/1425#discussioncomment-339343.
* Updates the schema to allow parameters to be set but unused based on https://github.com/FCP-INDI/C-PAC/discussions/1425#discussioncomment-339483, so any of the rows in the following table are valid settings:
| run | filter_type | breathing_rate_min | breathing_rate_max | center_frequency | filter_bandwidth | lowpass_cutoff |
| --- | --- | --- | --- | --- | --- | --- | 
| **off** | doesn't matter | doesn't matter | doesn't matter | doesn't matter | doesn't matter | doesn't matter | 
| on | **notch** | **required** | **required** | doesn't matter | doesn't matter | doesn't matter |
| on | **notch** | …

📝 Clarify valid `motion_estimate_filter` settings

---

CPAC/utils/configuration.py
dev/docker_data/run.py

Fixes
```Python
File "/code/run.py", line 479, in <module>
c.update(overrides)
TypeError: update() missing 1 required positional argument: 'val'
```
by @hahaai 
Moves the line where we convert the config dictionary to a Configuration object to after the `update`s from pipeline overrides. Adds an exception for trying to call `dict`'s `.update` on a `Configuration`.
Configurations have their own `update` method that takes a key and a value, while a dict's `update` takes another dict. The error above occurred because the pipeline overrides were being passed as a dict update to `c` after `c` was already converted to a `Configuration`
index.md`).
<details>
``` …
```

🐛 Cast config dict to Configuration class *after* overrides

---

CPAC/pipeline/schema.py

Fixes 
```Python
File "/code/run.py", line 474, in <module>
c = Configuration(c)
File "/code/CPAC/utils/configuration.py", line 110, in __init__
config_map = schema(config_map)
File "/usr/local/miniconda/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/miniconda/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/miniconda/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['nuisance_corrections']['2-nuisance_regression']['Regressors'][0]['Cerebr …
```

🐛 Add `include_*` keys to `Regressors` in validation schema

---

dev/docker_data/run.py

Fixes
```Python
Running the 'fmriprep-options' pre-configured pipeline.
File "/code/run.py", line 524, in <module>
c['pipeline_setup']['system_config']['max_cores_per_participant'], int(c['pipeline_setup']['system_config']['num_ants_threads'])
KeyError: 'num_ants_threads'
```
by @shnizzedy 
Related to #1435 by @shnizzedy 
1. Moves the conversion of a pipeline config dict to a Configruration object from after https://github.com/FCP-INDI/C-PAC/blob/1cbbdaf09ea6a1e90392ad00c4e18853e3118414/dev/docker_data/run.py#L484-L525 to before.
2. Sets imported pipleine base to ['anat-only'](https://fcp-indi.github.io/docs/nightly/user/preconfig#anat-only-default-with-anatomical-preprocessing-only) if `args.anat_only`
I overshot where to do this type conversion in …

🐛 Move pipeline import earlier in configuration process

---

CPAC/utils/yaml_template.py
dev/docker_data/run.py

I realized I never updated the step in `run.py` that writes the what-was-actually-run pipeline YAML file for #1411. Before this PR, the generated file just gives a minimal configuration showing what's different from the default. With this PR, both a full and minimal configuration are generated.
index.md`).
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```

🚸 Include both full and minimal pipeline_config YAML files at run

---

dev/docker_data/run.py

Fixes regtest-2‒4 in https://github.com/FCP-INDI/cpac_run_logs/issues/15#issue-811536953 by @shnizzedy
Before this change, if `n_cpus` < `num_participants_at_once`, `minimum_threads_per_subject` ends up at 0. With this PR, in that situation, `minimum_threads_per_subject` becomes `n_cpus` and `num_participants_at_once` becomes 1.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```

🩹 Keep `minimum_threads_per_subject` > 0

---

CPAC/pipeline/schema.py

- Improves validation of `motion_estimate_filter`
- Updates message when config is invalid for this key from 
> ```Python
> MultipleInvalid:  motion_estimate_filter configuration is invalid. for dictionary value @ data['motion_estimate_filter']
> ```
to 
> ```Python
> MultipleInvalid: `motion_estimate_filter` configuration is invalid. See https://fcp-indi.github.io/docs/v1.8.0/user/func#motion_estimate_filter_valid_options for details. for dictionary value @ data['motion_estimate_filter']
> ```
_https​://fcp-indi.github.io/docs/v1.8.0/user/func#motion_estimate_filter_valid_options_ will be something like
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and …
```

📝 Clarify `motion_estimate_filter` validation message

---

CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/resources/configs/pipeline_config_anat-only.yml

Fixes https://github.com/FCP-INDI/cpac_run_logs/issues/10 by @shnizzedy
* Turns https://github.com/FCP-INDI/C-PAC/blob/26fb1b6edd7c5356f3baa040fd7a1e0003f5e7eb/CPAC/resources/configs/pipeline_config_anat-only.yml#L147-L151 https://github.com/FCP-INDI/C-PAC/blob/26fb1b6edd7c5356f3baa040fd7a1e0003f5e7eb/CPAC/resources/configs/pipeline_config_anat-only.yml#L173-L175 to resolve the runtime error in https://github.com/FCP-INDI/cpac_run_logs/issues/10
* Moves https://github.com/FCP-INDI/C-PAC/blob/6b263d26203f1ac589d0ce1fe91e970d2c448fff/CPAC/pipeline/engine.py#L772 above https://github.com/FCP-INDI/C-PAC/blob/6b263d26203f1ac589d0ce1fe91e970d2c448fff/CPAC/pipeline/engine.py#L752-L770 to avoid 
```Python
File "/code/run.py", line 677, in <module>
test_config = …
```

🔧 Update `anat-only` preconfig to not run `coregistration` and `func_registration_to_template`

---

CPAC/pipeline/cpac_pipeline.py

Fixes 
> ```Python
>    210224-03:44:20,273 nipype.workflow WARNING:
>    Could not remove working directory /outputs/working/cpac_sub-105923
> ```
by @pab2163
* Refactors the working directory initialization to
1. check if the working directory is an s3 directory
2. if so, raise an error
3. check if the in-container user has write-access to the specified working directory path in the configuration
4. if not, set working directory `working` within the output directory
regardless of whether we're saving the working directory or not. 
* Also moves the resource overusage report above the run complete / did not execute cleanly message.
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, …
```

🐛 Fix working directory initialization

---

CPAC/pipeline/cpac_pipeline.py

Fixes #1450  by @ccraddock 
modifies the nipype config settings in cpac_pipeline.py to change the filetype of crashfiles to text
- run a CPAC pipeline known to crash
- rejoice in the human readable and grepable crashfiles!
- 
index.md`).
- [x ] My pull request targets the `develop_v1.8_convergence` branch of the repository. 
- [x ] My commit messages follow best practices.
- [x ] My code follows the established code style of the repository.
- [x ] I tried running the project locally and verified that there are no
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy …
```

changed crashfile format to text

---

CPAC/utils/monitoring/draw_gantt_chart.py

Drops the 
```
**threads**
runtime > limit
```
entries from the resource overusage report added in #1428. As mentioned in https://github.com/FCP-INDI/C-PAC/issues/1404#issuecomment-756389510 and https://github.com/nipy/nipype/pull/3290#issuecomment-756994047, I think the runtime threads are measuring something different than the estimated threads, so I don't think the comparison is intuitively meaningful. Also, the sheer number of nodes for which the runtime threads > estimated threads makes the report less manageable and obscures the memory overusage information.
```
nipype.workflow WARNING:
The following nodes used excessive resources:
---------------------------------------------
cpac_3699991
.anat_skullstrip_ants
.lap_tmpl
**memory_gb**
runtime > estimated
0.5595245361328125 > 0.2 …
```

🔇 Comment out runtime_threads ⩼  threads

---

CPAC/pipeline/schema.py
CPAC/pipeline/test/__init__.py
CPAC/pipeline/test/test_schema_validation.py

Fixes 
```Python
voluptuous.error.MultipleInvalid: not a valid value @ data['functional_preproc']['motion_estimates_and_correction']['motion_estimate_filter']['run'][0]
```
error message raised when `'run'` is set to `[True]` and something is invalid in the [`motion_estimate_filter` configuration](https://github.com/FCP-INDI/C-PAC/pull/1432#issue-568453434)
by @sgiavasis 
* Improves the specificity of validation for `motion_estimate_filter` by checking for `None`, `False`, and [`ExactSequence`](http://alecthomas.github.io/voluptuous/docs/_build/html/voluptuous.html#voluptuous.validators.ExactSequence)s `[]` and `[False]` as the only valid options for the no-estimate-filter option https://github.com/FCP-INDI/C-PAC/blob/e34beb8b7e10cd5116f5848ed6f0652b91c06ee1/CPAC/pipeline/schema.py#L498-L5 …

🥅 Improve handling of invalid 'motion_estimate_filter'

---

CPAC/generate_motion_statistics/__init__.py
CPAC/generate_motion_statistics/generate_motion_statistics.py
CPAC/generate_motion_statistics/test/test_dvars.py
dev/docker_data/required_afni_pkgs.txt

Given the strange problem with DVARS, I've implemented its computation using AFNI 3dTto1d. The problem vanished!
Fixes #1301 by @sgiavasis 
Instead of relying on Python code, this PR replaces the current DVARS code with an interface for AFNI's implementation of DVARS. Hopefully, it is more optimized given it is compiled etc. The pipeline does not hang anymore.
Yes.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```

Use AFNI to compute DVARS

---

CPAC/generate_motion_statistics/generate_motion_statistics.py
Dockerfile
variant-lite.Dockerfile

Playing around with the Docker container, trying to understand the DVARS issue (#1301), I got to a point in which a python interpreter console started to throw me errors when I've imported NumPy, complaining about problems loading the Intel MKL libs.
So, the DVARS was stucking the pipeline after raising a segfault. The weird thing is that, for ABIDE I, the problem was not present:
```
s3://fcp-indi/data/Projects/ABIDE/RawDataBIDS/NYU/ \
--n_cpus 8 \
--mem_gb 16 \
--output_dir s3://cnl-cpac-batch/abide-8.16 -- 0051159
```
however, for CORR and Rockland, the problem presents itself as described in every execution:
```
s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDSLatest \
--n_cpus 8 \
--mem_gb 16 \
--output_dir s3://cnl-cpac-batch/rockland-8.16 -- A00085066
```
and
``` …
```

Fix: a tale of a bug and a bad fix - the DVARS issue

---

CPAC/func_preproc/func_preproc.py
CPAC/nuisance/nuisance.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/pipeline/schema.py
CPAC/registration/registration.py
CPAC/resources/configs/pipeline_config_abcd-options.yml
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/seg_preproc/seg_preproc.py
dev/docker_data/default_pipeline.yml

Related to:
- #1393 by @SucyLi 
- #1270 by @sgiavasis
- #1227 by @HechengJin0 
- Node blocks can now have multiple run switches.
- T1-template and EPI-template registration pathways are no longer two sides of the same fork, but are two separate pathways. They can still be both run within the same pipeline, however.
- Added a ["blank" pipeline config](https://github.com/FCP-INDI/C-PAC/blob/feature/abcd_v1.8-tswarp-changes/CPAC/resources/configs/pipeline_config_blank.yml) as a preconfig, intended to be imported for convenient minimal pipeline configs. All run switches are set to `Off` in this pipeline config.
- EPI template outputs now delineated with `space-EPItemplate`.
- There are still some FSL-pipeline issues in the target branch that need resolution (details below under Tests). …

Multiple run switches and EPI-template registration cleanup

---

CPAC/anat_preproc/ants.py
CPAC/func_preproc/func_preproc.py
CPAC/generate_motion_statistics/generate_motion_statistics.py
CPAC/nuisance/nuisance.py
CPAC/nuisance/utils/__init__.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/pipeline/nipype_pipeline_engine/__init__.py
CPAC/pipeline/nipype_pipeline_engine/engine.py
CPAC/pipeline/plugins/__init__.py
CPAC/pipeline/plugins/legacymultiproc.py
CPAC/pipeline/test/test_nipype_pipeline_engine.py
CPAC/registration/output_func_to_standard.py
CPAC/registration/registration.py
CPAC/seg_preproc/seg_preproc.py
CPAC/timeseries/timeseries_analysis.py
CPAC/utils/configuration.py
CPAC/utils/test_mocks.py
CPAC/utils/utils.py
CPAC/vmhc/utils.py
CPAC/vmhc/vmhc.py
dev/docker_data/bids_utils.py
dev/docker_data/run.py

Fixes #1480 by @shnizzedy
Fixes #1511 by @shnizzedy
Adds an optional `mem_x` parameter that takes a tuple of `(multiplier, Node_property_containing_filename)` to set memory estimates dynamically.
`mem_gb` remains a constant, such that
if `mem_x` is not set, `node.mem_gb` = `mem_gb`
if `mem_x` is set, `node.mem_gb` = `mem_gb + mem_x[0] * size_of(get_attr(node.inputs, mem_x[1]))`
https://github.com/FCP-INDI/C-PAC/blob/e67246cb2a157048eea44aacc18c19ab087d0b9f/CPAC/pipeline/test/test_nipype_pipeline_engine.py#L31-L63
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```

⚡️ Make memory estimates data-dependent

---

CPAC/nuisance/nuisance.py

Related to #1479 by @zeosmar
Appends the index of each custom regressor file to the node name. 
Prior to this change, when multiple custom regressor files were provided for a given regression, each would be assigned to a node with the same name.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the …
```

🐛 Include index in name for each custom regressor file

---

CPAC/pipeline/nipype_pipeline_engine/__init__.py
CPAC/pipeline/nipype_pipeline_engine/engine.py
CPAC/pipeline/plugins/legacymultiproc.py

Related to #1480 by @shnizzedy 
Fixes FileNotFoundError `[Errno 2] The memory estimate for Node 'CerebrospinalFluid_2mm_flirt' depends on the input 'in_file' but no such file or directory: <undefined>`
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```

:bug: Apply global UNDIFINED_SIZE in prerun check if FileNotFound

---

CPAC/pipeline/plugins/legacymultiproc.py

Related to #1506 by @shnizzedy 
To precisely estimate memory usage in the node scheduling algorithm, the main process memory must be accounted for. In some scenarios, the resident memory can reach 3GB, which can cause malfunctioning in the pipeline execution. This PR accounts for the main process memory usage in the scheduling.
Using the `resource` package to get the peak of resident memory, the peak memory usage is subtracted from the memory available for nodes to run in the Multiproc plugin.
- Several C-PAC runs on AWS
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```

[Feature] Estimate main process memory usage

---

dev/docker_data/run.py

Fixes #1526 by @anibalsolon 
The script considers the participant_ndx parameter when it is equal to 0.
0 evaluates to false, so it was like it was not being provided. Checking if it is None differentiates the scenarios of when it is zero and when it is not provided.
```
docker run fcpindi/c-pac:latest s3://fcp-indi/data/Projects/CORR/RawDataBIDS/IBA_TRT/ /output test_config --participant_ndx 0
```
runs only once.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate of …
```

[Bugfix] Consider participant ndx parameter when = 0

---

CPAC/pipeline/schema.py

Fixes a bug introduced in #1529 by @shnizzedy
Fixes bug that causes
```Python
Error details:
expected int @ data['segmentation']['tissue_segmentation']['ANTs_Prior_Based']['CSF_label'][0]
```
if a 1.8.1-syntax config is provided.
While `GM_label` and `WM_label` combined `left_` and `right_` items into new keys, `CSF_label` just changed from an integer to a list without any change to the label, so the updater function was thinking `CSF_label` needed to be updated if preset, giving dictionaries like
```Python
{'GM_label': [3, 42], 'WM_label': [2, 41], 'CSF_label': [[24]]}
```
This PR updates the updater to check if a value is already a list, and if so, appends the value's items to the new list instead of the list itself. 
https://github.com/FCP-INDI/C-PAC/blob/cfacfce1f8c3f785820b1f0680991cb …

🐛 Don't put `CSF_label` in a list of lists

---

CPAC/nuisance/nuisance.py
CPAC/pipeline/engine.py

Fixes the recent WM and CSF regressor crash in the current `develop` branch.
The nature of the `check_rpool()` member function of `ResourcePool` would cause certain instances of "listed" inputs to return False when something further down the list was actually present.
This should enable the fx-options preconfig to run properly without crashes.
<details>
```
Version 1.1
Suite D4700
(a) …
```

Fixed a bug in the check_rpool() member function of ResourcePool.

---

CPAC/nuisance/nuisance.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/registration/registration.py
CPAC/registration/utils.py
CPAC/resources/configs/pipeline_config_rodent.yml

Fixes #1494 by @XinhuiLi 
- Important change to the connection engine such that the strategy/resource provenance is now more exhaustive and allowed for nuisance regressor calculation, and nuisance regression itself, to be split.
- Split nuisance regressors and nuisance regression into two node blocks.
- Cleaned up required/optional inputs for nuisance regressors and regression to make it easier to run EPI-only or rodent pipelines.
- NOTE: It may seem there are extra regressor TSV outputs being written when nuisance is set to [On, Off], when the strategy includes bandpass filtering.
- However, it is simply writing out the original regressors, and the bandpass filtered regressors - the filtered regressors will have the `nuisance_regression` label in `CpacVariant` alongside the regression …

More exhaustive CpacProvenance - split nuisance - EPI-only streamlines

---

CPAC/nuisance/nuisance.py
CPAC/nuisance/utils/__init__.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py
CPAC/registration/registration.py

Fixes an issue in the `develop` branch regarding EPI-only pipelines and nuisance.
- More work is needed to make it easier to use a ventricles mask for CSF regression, if a CSF mask is not present or if segmentation is not enabled.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```

Nuisance regression flexibility for EPI-only pipelines

---

CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/plugins/legacymultiproc.py

Related to #1480 & #1509 by @shnizzedy 
Fixes a bug where multicore runs were not logging resource usage.
In #1499, this initialization https://github.com/FCP-INDI/C-PAC/blob/44ac6a6ebd69ab908788deb2d5cfa09ce5ef6f2c/dev/docker_data/run.py#L667-L669 doesn't yet have https://github.com/FCP-INDI/C-PAC/blob/44ac6a6ebd69ab908788deb2d5cfa09ce5ef6f2c/CPAC/pipeline/cpac_pipeline.py#L445, so Nipype defaults to logging without monitoring. Instead of setting logging at that point, this PR updates our customized `LegacyMultiProcPlugin` to always initialize with resource montioring: https://github.com/FCP-INDI/C-PAC/blob/a1b72867d5e389df669115f4e2fefe0eb325cc69/CPAC/pipeline/plugins/legacymultiproc.py#L28-L35
<details>
```
Developer Certificate of …
```

🔊 Restore status callback

---

Dockerfile
variant-ABCD-HCP.Dockerfile
variant-fMRIPrep-LTS.Dockerfile

Prevents FreeSurfer from looking for nonexistant `~/matlab/startup.m` during setup.
References
* > it is not a problem if you're not going to run FS-FAST. If it 
bugs you, you can
setenv NO_FSFAST 1
― [:email: Re: [Freesurfer] Set Up question. Doug Greve](https://www.mail-archive.com/freesurfer@nmr.mgh.harvard.edu/msg29371.html)
* ```BASH
echo "5. If NO_FSFAST is set (to anything), "
echo "   then the startup.m stuff is ignored."
```
― [TimVanMourik/OpenFmriAnalysis@`8cec6d3`/Core/FreeSurferEnv.sh#L39-L40](https://github.com/TimVanMourik/OpenFmriAnalysis/blob/8cec6d3c21e7939515349946919708645138bcd3/Core/FreeSurferEnv.sh#L39-L40)
```
Loading 🐳 Docker
Loading 🐳 fcpindi/c-pac:nightly with these directory bindings:
local                                       Docker …
```

🔇 Prevent SetUpFreesurfer from trying to load Matlab

---

dev/docker_data/run.py

Fixes #1549 by @shnizzedy
#1549 resolves the issue for MultiProc by moving the callback initialization into the the custom plugin initialization, but for Linear we use the built-in plugin. This PR restores the `status_callback` initialization in `plugin_args` in `run.py` to allow Linear to also log resource usage.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```

🔊 Restore resource logging for linear plugin

---

CPAC/anat_preproc/anat_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/resources/configs/pipeline_config_fmriprep-options.yml

Fixes #1567 by @sgiavasis
Fixes an error in `v1.8.1-develop`.
- Restores the original skull-stripped T1-brain output for the `niworkflows_ants` brain extraction workflow.
- Fixes an error (in `develop`) with the timeseries warp-to-template node block changes that would block the pipeline from running during `fmriprep-options` preconfig runs, if `create_regressors` was enabled.
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```

Update and fix fmriprep-opts preconfig related changes

---

dev/docker_data/run.py

This fix allows for use of parameter `num_ants_threads` in the command line, without having to modify a pipeline config. 
Fixes #1563  by @amygutierrez 
This pull request will allow for a parameter `--num_ants_threads {number}` to be used in the command line when creating a docker run. This is helpful to easily change the number of cores to allocate to ANTS-based anatomical registration per participant.
Added `parser.add_argument('num_ants_threads')` to lines 290 and added if-loop for different conditions in line 561 of code run.py
Pulled this branch into the server and ran using s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS/NYU dataset and 1 subject. Two separate runs were done. 
First docker run: 
`docker run --security-opt=apparmor:unconfined -v /home/agutierrez/Documents/C-PAC:/code …

Added argument num_ants_threads to run.py. 

---

CPAC/seg_preproc/seg_preproc.py

Making sure that if use_priors is used, that it uses xfm. otherwise, xfm = None.
This pull request will assign `...image_desc-linear_xfm` if `use_priors` is turned on. Otherwise, xfm is not used. 
Used a blank default pipeline and set `use_priors` to `Off`. No longer receiving this error `KeyError: "When trying to connect node block 'tissue_seg_ants_prior' to workflow 'cpac_sub-5289383_ses-1' after node block 'correct_restore_brain_intensity_abcd': from-template_to-T1w_mode-image_desc-linear_xfm"` Since `use_priors` is off, then xfm is not being used, therefore `from-template_to-T1w_mode-image_desc-linear_xfm` should not be used either.
- [ x] My commit messages follow best practices.
- [ x] My code follows the established code style of the repository.
<details>
<summary>Developer …

Use_priors correction: using xfm when turned On only

---

CHANGELOG.md
CPAC/anat_preproc/anat_preproc.py
CPAC/func_preproc/func_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/registration/registration.py
CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
CPAC/resources/cpac_templates.csv
CPAC/seg_preproc/seg_preproc.py

Fixes T2 data flow and pipeline connections in `develop`
Recent updates to the NHP pipeline integrate T2 processing, if T2 data is present. Some fixes were necessary based on recent testing.
<details>
```
Version 1.1
Suite D4700
(b) The …
```

Fix some T2 and NHP-related connections

---

CPAC/pipeline/cpac_pipeline.py

Fixes #1645 by @shnizzedy 
Depending on one's pipeline configuration between #1645 and this PR, `verbose_logger` would be set to `None` here https://github.com/FCP-INDI/C-PAC/blob/ffac4a02cc7fc0175f7207bf8620d5fcba8d6c6f/CPAC/pipeline/cpac_pipeline.py#L1051 which would raise an `AttributeError` here https://github.com/FCP-INDI/C-PAC/blob/ffac4a02cc7fc0175f7207bf8620d5fcba8d6c6f/CPAC/pipeline/cpac_pipeline.py#L1052
Nipype's [`getLogger`](https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/utils/logger.py#L90-L98) relies on [`nipype.utils.logger.Logging`'s `loggers` attribute](https://github.com/nipy/nipype/blob/6c060304f380c46b2f05c5afdc7171dbbdfadc58/nipype/utils/logger.py#L40-L45), which does not include `'engine'`.
Built-in `logging.getLogger` does not …

🐛 Import engine logger with built-in logging library

---

CPAC/pipeline/engine.py

Related to setup taking forever with this pipeline config
```YAML
FROM: abcd-options
pipeline_setup:
pipeline_name: ABCD-blip
output_directory:
quality_control:
generate_xcpqc_files: On
functional_preproc:
distortion_correction:
using:
- PhaseDiff
- Blip
```
Adds lengths of `strat_list_list` and `rp_dct` to engine.log
> I found a couple really good spots where we can add reports for verbose logging/debugging, to help quickly figure out these forking issues in the future. Check the length of strat_list_list right before this loop: https://github.com/FCP-INDI/C-PAC/blob/a33dfe892ce3cd31d346f3c1ab032e7e91e4ba0f/CPAC/pipeline/engine.py#L436, and you get something like this:
>
> ```
> 220203-07:26:12,186 nipype.workflow INFO:
>         Connecting n4_bias_correction...
> 220203-07:26:12,187 …
```

🔊 Add lens of `strat_list_list` and `rp_dct` to engine.log

---

CPAC/cwas/tests/test_cwas.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/nipype_pipeline_engine/__init__.py
CPAC/pipeline/nipype_pipeline_engine/engine.py
CPAC/pipeline/nipype_pipeline_engine/plugins/__init__.py
CPAC/pipeline/nipype_pipeline_engine/plugins/cpac_nipype_custom.py
CPAC/pipeline/random_state/seed.py
CPAC/pipeline/schema.py
CPAC/qc/xcp.py
CPAC/seg_preproc/seg_preproc.py
CPAC/seg_preproc/utils.py
CPAC/utils/interfaces/netcorr.py
CPAC/utils/monitoring/__init__.py
CPAC/utils/utils.py
CPAC/utils/yaml_template.py
dev/circleci_data/test_external_utils.py

Fixes
> :flushed: And I've apparently been doing the [specific-violation for flake8](https://flake8.pycqa.org/en/latest/user/violations.html#in-line-ignoring-errors) wrong:
> without the colon the part after `# noqa` would be ignored
― [![Slack](https://cdn.brandfolder.io/5H442O3W/at/pl546j-7le8zk-6gwiyo/Slack_Mark.png?width=12&height=12) DM](https://cmi-cnl.slack.com/archives/D02F35ESMGR/p1643388726771659) @shnizzedy
Related to https://github.com/FCP-INDI/C-PAC/pull/1639#pullrequestreview-865304168 by @shnizzedy
* Adds colons to `# noqa` where no colon was present but a specific code was provided
* Removes `# noqa` where no code was provided
* Adds `# pylint: disable` to lines that had `# noqa` but no `# pylint: disable` and Pylint complained about style
<details>
<summary>Developer …

🚨 Fix `  # noqa` specificity

---

CPAC/anat_preproc/anat_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/surface/tests/test_config.py
CPAC/utils/configuration.py
dev/circleci_data/requirements.txt
dev/docker_data/default_pipeline.yml

Related to #1653 by @shnizzedy & @sgiavasis 
If `anatomical_preproc.['brain_extraction']['using']` includes `'FreeSurfer-ABCD'`, force `surface_analysis['freesurfer']['run']` to be off.
> in the ABCD preconfig both freesurfer_preproc is enabled and
> freesurfer_abcd_preproc is enabled and it's causing two strats for
> freesurfer-subject-dir which causes the FS-ABCD brain mask node block
> to fork unnecessarily, which then starts multiplying uncontrollably. I
> turned this off and the pipeline runs immediately for PNC data.
> recon-all still gets a chance to run in freesurfer abcd preproc.
― Steve on Slack
Passes if pipeline builds in less than a minute:
https://github.com/FCP-INDI/C-PAC/blob/ee734cab1e6f7e2fe11762aeebab126afb058aea/CPAC/surface/tests/test_config.py#L13-L26
<details> …

🐛 Don't run `recon-all` twice

---

CPAC/cwas/tests/test_pipeline_cwas.py

Fixes https://github.com/FCP-INDI/C-PAC/pull/1691#issuecomment-1054707819 by @shnizzedy 
If https://github.com/FCP-INDI/C-PAC/blob/c95f25626e0e506a8eb386c39140ef41336b34c2/CPAC/cwas/tests/test_pipeline_cwas.py#L14 fails, skips this whole test: https://github.com/FCP-INDI/C-PAC/blob/c95f25626e0e506a8eb386c39140ef41336b34c2/CPAC/cwas/tests/test_pipeline_cwas.py#L11-L66
By skipping the whole test, we do lose out on this assertion https://github.com/FCP-INDI/C-PAC/blob/c95f25626e0e506a8eb386c39140ef41336b34c2/CPAC/cwas/tests/test_pipeline_cwas.py#L33-L37 that could run without this atlas, but https://github.com/FCP-INDI/C-PAC/blob/c95f25626e0e506a8eb386c39140ef41336b34c2/CPAC/cwas/tests/test_pipeline_cwas.py#L38-L66 seems to be the real test here, with the part we're maybe-unnecessarily …

✅ Skip test if `nilearn.datasets.fetch_atlas_craddock_2012()` fails

---

CHANGELOG.md
CPAC/resources/configs/pipeline_config_rodent.yml

Uses the correct templates for the rodent pipeline. Pipelines were provided by Marco Pagani. 
Fixes #1675 by @shnizzedy 
Templates `chd8_functional_template_sk.nii` and `chd8_functional_template_noise_mask_ag.nii` were added into this repo for the rodent pipeline. `chd8_functional_template_sk.nii.gz` is the brain template that you use for registration, `chd8_functional_template_noise_mask_ag.nii.gz` is the ventricle mask of the brain template that you use to extract signal for denoising
Template chd8_functional_template_sk.nii was used in:
```
registration_workflows:
fuctional_registration:
EPI_registration:
EPI_template: chd8_functional_template_sk.nii
registration_workflows:
functional_registration:
func_registration_to_template:
target_template:
EPI_template:
EPI_template_funcreg: …
```

Rodent template fix

---

.flake8
CHANGELOG.md
CPAC/func_preproc/func_preproc.py
CPAC/utils/interfaces/ants.py

Fixes #1556 by @shnizzedy 
>  If `CopyImageHeaderInformation` does not work, you can use `SetOrigin`, and if necessary `SetDirectionByMatrix`, to set both image headers to a constant reference value.
― [_ANTsX/ANTs Wiki_: Inputs do not occupy the same physical space: Fixing precision errors](https://github.com/ANTsX/ANTs/wiki/Inputs-do-not-occupy-the-same-physical-space#fixing-precision-errors)
* In #1531, we set up `CopyImageHeaderInformation`, which reduced but did not eliminate occurrences of this error.  Here we use ANTs to grab the dimensions from the mask header and set them on the timeseries file.
* While I was updating [`CPAC/utils/interfaces/ants.py`](https://github.com/FCP-INDI/C-PAC/blob/28f8bc0a53f71cbdce4f553a41c3fd95ca06ad47/CPAC/utils/interfaces/ants.py), add source license …

🐛 Fix: `itk::ERROR: […] Inputs do not occupy the same physical space`

---

CHANGELOG.md
CPAC/utils/monitoring/draw_gantt_chart.py

```Python
File "/code/run.py", line 798, in <module>
run_main()
File "/code/run.py", line 779, in run_main
test_config=(1 if args.analysis_level == "test_config" else 0)
File "/code/CPAC/pipeline/cpac_runner.py", line 567, in run
raise e
File "/code/CPAC/pipeline/cpac_runner.py", line 564, in run
p_name, plugin, plugin_args, test_config)
File "/code/CPAC/pipeline/cpac_pipeline.py", line 720, in run_workflow
num_cores_per_sub, logger)
File "/code/CPAC/utils/monitoring/draw_gantt_chart.py", line 561, in resource_report
generate_gantt_chart(callback_log, num_cores)
File "/code/CPAC/utils/monitoring/draw_gantt_chart.py", line 368, in generate_gantt_chart
for i in nodes_list
File "/code/CPAC/utils/monitoring/draw_gantt_chart.py", line 369, in <listcomp>
if …
```

♻️ Handle timestamps with or without nanoseconds

---

CPAC/pipeline/engine.py

~~Related to #1728 by #shnizzedy~~
Fixes bug in error handling in which error message was including the literal string `{resource_list}` instead of the contents of the variable `resource_list`
~~From a direct message thread on Slack with @gkiar, tweaks the RBCv0 config to work around #1728~~
~~Reverts motion correct tool to MCFLIRT.~~
~~Rerunning RBC exemplars with the updated config~~
<details>
```
Version 1.1
Suite D4700
By making a …
```

🥅 Fix LookupError transclusion

---

CPAC/func_preproc/func_preproc.py
CPAC/utils/docs.py

Running in Docker on a server with apparmor on and without the `--security-opt=apparmor:unconfined` Docker flag crashes with `URLError`.
Catches `ContentTooShortError` & `URLError` and handles them the same as handling `HTTPError`
de7666068615154399c15d7948ba141f18bc1bdc is just a fix for a merge error from #1733; I already cherry-picked it into `develop` @ 815779d53888227d688bd505e2bc94995671a6b3
<details>
```
Version 1.1
Suite D4700
By making …
```

Catch any urllib error

---

CPAC/func_preproc/func_preproc.py
CPAC/pipeline/schema.py

Fixes #1766  by @tergeorge 
This PR would make it possible for the user to assign "End" or "None" as the stop_idx value for time series extraction. 
Added the following test condition to func_preproc.py
```
if (stop_idx in [None, "End"]) or (int(stop_idx) > (nvols - 1)):
stopidx = nvols - 1
else:
stopidx = int(stop_idx)
return stopidx, startidx
```
To test this PR, do the following:
1. Create a pipeline config file with functional_preproc -> truncation -> stop_tr as End
2. Run CPAC with the pipeline config file updated as instructed in step 1.
The pipeline should run to completion without any errors.
<details>
```
Version 1.1
1 Letterman …
```

/Fix/assign_stopidx_asend

---

CHANGELOG.md
CPAC/resources/configs/pipeline_config_rbc-options.yml

Fixes #1767 by @sgiavasis 
Updates the `rbc-options` preconfig to use 2mm version of the atlases, for time series extraction and connectome computation.
As the `rbc-options` preconfig sets the functional data write-out to 2mm resolution, having the atlases in the same resolution will prevent the unnecessary extra operation of resampling the 1mm version of the atlases down to 2mm.
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```

Change rbc-options atlases to 2mm versions

---

CHANGELOG.md
CPAC/info.py
CPAC/longitudinal_pipeline/longitudinal_workflow.py
CPAC/pipeline/check_outputs.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/pipeline/schema.py
CPAC/pipeline/test/test_schema_validation.py
dev/docker_data/default_pipeline.yml
requirements.txt

Fixes #1774 by @shnizzedy 
Maybe fixes #1308 by @cbin-cnl
Related to #1777 by @shnizzedy 
When the same subject is run through multiple pipelines with the same top-level output directory, not saving the working directory, the top of the tree looks something like
```tree
.
├── log
│   ├── pipeline_fmriprep-options±topup
│   ├── pipeline_RBCv0
│   └── pipeline_RBCv0-noNuisanceRegression
├── output
│   ├── cpac_fmriprep-options±topup
│   ├── cpac_RBCv0
│   └── cpac_RBCv0-noNuisanceRegression
└── working
├── cpac_sub-1_ses-1
…
```
so for any given subject-session, a race condition exists where whichever finishes first will clean up and erase the working directory that the other pipeline(s) are still using, leading to various missing file errors and ultimately crashes.
I'm also not sure what …

🚚 Use `f'pipeline_{pipeline_name}'` subdirectories for `log`, `working`, and `output`

---

CHANGELOG.md
CPAC/utils/yaml_template.py

Fixes #1776 by @shnizzedy
Related to #1774 & #1775 by @shnizzedy 
Before this PR, C-PAC would generate run-specific config files like
```BASH
cpac_data_config_{timestamp}.yml
cpac_pipeline_config_{timestamp}.yml
```
With this PR, those filenames include the first 8 characters of the hexadecimal digest of a hash of all `site_id`s, `subject_id`s, and `unique_id`s (like `site1,site2,site3_sub1,sub2,sub3_uid1,uid2,uid3`) in the given data config.
```BASH
cpac_data_config_{data_hash}_{timestamp}.yml
cpac_pipeline_config_{data_hash}_{timestamp}.yml
```
<a name="collision-note"></a>
**NOTE**: #1774 is still relevant if running multiple configs to the same top-level output directory (if the same data config launches multiple pipeline configs in the same second, this behavior will persist after …

🐛 Differentiate sametime data and pipeline configs

---

CHANGELOG.md
CPAC/alff/alff.py
CPAC/nuisance/nuisance.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/pipeline/schema.py
CPAC/registration/registration.py
CPAC/reho/reho.py
CPAC/resources/configs/pipeline_config_default.yml

Allow ReHo and ALFF to be calculated after timeseries warps to template space.
Adding node blocks to `reho.py` and `alff.py` that allows `space-template_*` inputs so that these derivatives can be calculated in template space. 
Default pipeline was changed to choose whether to run these derivatives in `Template` or `Native` space. The default is in 'Native` space.
```
amplitude_low_frequency_fluctuation:
run: On
target_space: Native
highpass_cutoff: [0.01]
lowpass_cutoff: [0.1]
regional_homogeneity:
run: On
target_space: Native
cluster_size: 27
```
`cpac_pipeline.py` will check whether the input for these derivatives is `Template` or `Native` and then will run the respective node block. 
```
if 'Native' in target_space_alff:
if not rpool.check_rpool('alff'):
pipeline_blocks += [alff_falff] …
```

Calculate ReHo and ALFF in template space

---

CHANGELOG.md
CPAC/distortion_correction/distortion_correction.py
CPAC/pipeline/cpac_pipeline.py
CPAC/registration/registration.py
dev/docker_data/run.py

Related to #1242 by @sgiavasis 
Applies the AFNI 3dQwarp or FSL TOPUP distortion correction un-warps (derived from EPI field map data).
Current workflows, 3dQwarp produces an ANTs warp field, and TOPUP produces an FSL warp field. These cannot be converted interchangeably, so when the pipeline is using the opposite tool for registration, these warps need to be applied specifically on their own.
<details>
```
Version 1.1
Suite D4700
By making a …
```

Address transform mismatch (ANTs/FSL) when applying blip warp

---

CHANGELOG.md
CPAC/func_preproc/func_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_rbc-options.yml

Fixes #1812 by @sgiavasis 
Users can now select to run AFNI 3dDespike on template-space BOLD data.
The toggle can be found in the pipeline config YAML under the despiking segment.
Space: ['native', 'template']
<details>
```
Version 1.1
Suite D4700
indicated in the …
```

AFNI 3dDespike in template space

---

CHANGELOG.md
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/resources/configs/pipeline_config_rbc-options.yml
dev/docker_data/run.py

Subset of #1789 / #1814
Related to https://github.com/FCP-INDI/TheWay/issues/8 by @shnizzedy
Exposes Nipype's `stop_on_first_crash` configuration option with new `fail_fast` config option
<details>
```
Version 1.1
Suite D4700
(b) The …
```

🔧 Add `fail_fast` to expose Nipype's `stop_on_first_crash`

---

CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/nipype_pipeline_engine/__init__.py
CPAC/pipeline/nipype_pipeline_engine/engine.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/resources/configs/pipeline_config_rbc-options.yml

Resolves https://github.com/FCP-INDI/C-PAC/discussions/1502 by @shnizzedy 
* Updates Nipype dotfile creation to handle `-`s in node names to reenable Nipype's built-in ability to generate workflow flowcharts like the examples in https://github.com/FCP-INDI/C-PAC/discussions/1502#discussion-3353931
* Exposes the graph creation options in the pipeline config https://github.com/FCP-INDI/C-PAC/blob/fa46258257be19e2a7363df885638ff129dd6f56/CPAC/resources/configs/pipeline_config_default.yml#L82-L93
* Just adds quotation marks around the names to differentiate between dashes in names and dotfile semantic `-`s
* I included the level `entire_workflow` to leave room for a per-output provenance graph in the future without having to change the nesting level at that point
These graphs can be massive …

🔊 Customize dotfile creation for visualizing workflows

---

.github/workflows/check_updated_preconfigs.yml

Turns off PR CI triggers since the runs should already be triggered by push
<details>
```
Version 1.1
Suite D4700 …
```

👷 Reduce CI workflow duplication

---

CPAC/pipeline/engine.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_rbc-options.yml
CPAC/resources/templates/BIDS_identifiers.tsv
CPAC/resources/templates/__init__.py
CPAC/resources/templates/lookup_table.py
CPAC/utils/datasource.py
CPAC/utils/utils.py

Related to https://github.com/FCP-INDI/C-PAC_templates/issues/4, #1641, & #1808 by @shnizzedy 
With #1825, this PR is fully included in #1831, so if all three are approved, we can just merge #1831 and get all three without having to do any merge conflict resolution.
For the atlases used in `rbc-options`,
* adds the atlases to [`CPAC/resources/templates/BIDS_identifiers.tsv`](https://github.com/FCP-INDI/C-PAC/blob/3cf67687c0d24c24f8a4996e7c6d37795170fb34/CPAC/resources/templates/BIDS_identifiers.tsv)
* replaces `f'atlas-{strip_extension(basename(atlas_filename))}'` with `f'atlas-{atlasname}'` or `f'atlas-{atlasname}_desc-{atlasdesc}'` in derivative filenames
(for example,
```
sub-NDARYX806FL1_ses-HBNsiteRU_task-rest_run-1_atlas-Schaefer2018space-FSLMNI152res-2mmdesc-1000Parcels17NetworksOrd …
```

🎨 Standardize naming for atlases used in RBC

---

CPAC/utils/utils.py

Related to #1808 by @shnizzedy 
With #1823, this PR is fully included in #1831, so if all three are approved, we can just merge #1831 and get all three without having to do any merge conflict resolution.
1. Collects BIDS entities in `out_filename` by key
2. Converts all `-`s in values and duplicate keys to a single camelCase entity
3. Recombines the entities into a single `_`-delimited string
https://github.com/FCP-INDI/C-PAC/blob/e1960563981f1149165e7e36814d91a1de4b8b00/CPAC/utils/utils.py#L185-L187
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies …
```

🎨 Change `-`s in BIDS values to camelCase

---

CPAC/qc/xcp.py
CPAC/registration/registration.py

Updates XCPQC node block and new node blocks from #1820 by @sgiavasis to specify templates for renaming via functionality added in #1819 by @sgiavasis 
These upgrades were completed in parallel. This PR addresses a gap in the overlap.
No unspecified `template`s in ![expectedOutputs](https://user-images.githubusercontent.com/5974438/201148129-2c276c53-ab86-47b0-88d7-366e6b819bda.png)
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```

🎨 Add template specification to new outputs from #1820

---

CHANGELOG.md
CPAC/func_preproc/func_preproc.py
CPAC/pipeline/engine.py
CPAC/pipeline/schema.py
CPAC/pipeline/test/test_schema_validation.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/utils/bids_utils.py
CPAC/utils/utils.py

Fixes #1711 by @shnizzedy & @pab2163
1. Changes `functional_preproc.motion_estimates_and_correction.motion_estimate_filter` from a single filter to a list of filters
2. Forks on that list and/or `run`: `On` / `Off`
* This change will require an update to the GUI to generate filters similar to how [regressors and handled specially](https://github.com/FCP-INDI/C-PAC_GUI/blob/5ad6968d6b024191e6426253ee81e464b0f2ba88/app/containers/pipeline/parts/Regressor.jsx).
* In [a :thread: in ![Slack](https://camo.githubusercontent.com/4a2280bbe1168cbab989535aae3624962d9d03df0907f6cd3012ecc5ebb41b24/68747470733a2f2f63646e2e6272616e64666f6c6465722e696f2f35483434324f33572f61742f706c3534366a2d376c65387a6b2d36677769796f2f536c61636b5f4d61726b2e706e673f77696474683d3132266865696768743d3132)`DANLAB/C-PAC#general …

👔 Fork on `motion_estimate_filter.filters`

---

.github/workflows/smoke_test_participant.yml
CPAC/anat_preproc/anat_preproc.py
CPAC/registration/registration.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
CPAC/resources/configs/pipeline_config_regtest-3.yml
CPAC/resources/configs/pipeline_config_regtest-4.yml
CPAC/resources/configs/pipeline_config_rodent.yml

<table><tr><th>fixes</th><th>in</th></tr>
<tr><td><code>KeyError: 'run'</code></td><td>ff0172fc1a336947407e0ad7435fd8de5490e088</td></tr>
<tr><td>
#1840 /
```Python
LookupError: When trying to connect node block 'alff_falff_space_template' to workflow 'cpac_0025453_10' after node block 'timeseries_extraction_AVG': 
[!] C-PAC says: None of the listed resources are in the resource pool:
space-template_res-derivative_desc-bold_mask
```
</td><td>#1841?</td></tr>
<tr><td>
```Python
LookupError: When trying to connect node block 'bold_mask_ccs' to workflow 'cpac_0025453_10' after node block 'motion_correction_only': 
[!] C-PAC says: None of the listed resources are in the resource pool:
FSL-AFNI-bold-ref
```
</td><td>4f08a322aa2101a94cea1ff8328a5625afa35d49</td></tr>
<tr><td>
```Python …
```

✅ Smoke tests: Fix failing

---

CPAC/easy_thresh/easy_thresh.py

Add missing imports to easy_thresh module and make an unescaped regex string literal raw.
I wonder how this was able to run before.
- I ran the tests locally in docker
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

easy_thresh: Add missing imports; Fix regex escaping

---

CPAC/pipeline/engine.py
CPAC/pipeline/utils.py

Fixes
* > The expectedOutputs after [that merge](https://github.com/FCP-INDI/C-PAC/pull/1841) still have some `space-template` derivatives.
> ![screenshot of expectedOutputs with `space-template` filenames](https://user-images.githubusercontent.com/5974438/202276034-1c648c6d-9c5b-458a-9575-bbe2e6c5e36d.png)
by @shnizzedy
* Some unintended behavior where unnamed forks in a forking pipeline were getting collapsed into a single output in a chain like  `desc-1_vmhc` → `desc-1_desc-1_vmhc` → `desc-1_desc-1_desc-1_vmhc` → `desc-111_vmhc`
For `space-template` resources that don't have `Template` specified, climb the `CpacProvenance` recursively until either finding a `Template` (in which case it applies the first one it finds ― the assumption is we're not changing templates along the way) or it …

👔 Climb the provenance tree to set template name

---

CPAC/anat_preproc/anat_preproc.py
CPAC/func_preproc/func_preproc.py
CPAC/network_centrality/pipeline.py
CPAC/nuisance/nuisance.py
CPAC/pipeline/cpac_group_runner.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/qc/pipeline.py
CPAC/registration/registration.py
CPAC/resources/cpac_outputs.tsv
CPAC/resources/templates/BIDS_identifiers.tsv
CPAC/sca/sca.py
CPAC/timeseries/timeseries_analysis.py
CPAC/utils/bids_utils.py
CPAC/utils/configuration/configuration.py
CPAC/utils/utils.py

Related to #1808 by @shnizzedy 
* [Updates](https://github.com/FCP-INDI/C-PAC/commit/27c383bca94cdd4d19670a56dfe393ea3d5ca53a#diff-e1c8f266fdc8a7a1b635c8807fb98daa856518b7e16fd15905c31a5e5184b3e8) network centrality resource names per [BEP012](https://docs.google.com/document/d/16CvBwVMAs0IMhdoKmlmcm3W8254dQmNARo-7HhE-lJU)
* [Renames](https://github.com/FCP-INDI/C-PAC/commit/fd8bafccd252455baf2a97d15cdef03522debbcd) `res-[A-Za-z0-9]*` output entities to use actual resolution from sidecar
* [Updates](https://github.com/FCP-INDI/C-PAC/commit/1101e3de82b0433e40f585aaaa111028c0498c3e#diff-9b28de95c69080546f6835010600c40eae05103f411a7cd50eb20e188416243f) timeseries analysis to use `desc-preproc_bold` instead of `desc-brain_bold` 
* [Renames](https://github.com/FCP-INDI/C-PAC/commit/56b58c4fea87 …

🚚 RBC Output directory upgrades Pt. 11

---

CPAC/anat_preproc/anat_preproc.py

Crash with abcd-options brain_extraction
**Crash**
```
RuntimeError: Command:
3dcalc -a /ocean/projects/med220004p/agutierr/reg_test_1.8.5/bugfix_runs/with_data_configs_formatted/abcd-options/working/pipeline_abcd-options-seed/cpac_sub-NDARAD481FXF_1/anat_reorient_0/sub-NDARAD481FXF_T1w_resample.nii.gz -b /ocean/projects/med220004p/agutierr/reg_test_1.8.5/bugfix_runs/with_data_configs_formatted/abcd-options/working/pipeline_abcd-options-seed/cpac_sub-NDARAD481FXF_1/brain_mask_to_t1_restore_104/wmparc_maths_fill_holes_maths_warp.nii.gz -expr "a*step(b)" -prefix sub-NDARAD481FXF_T1w_resample_calc.nii.gz
Standard output:
Standard error:
++ 3dcalc: AFNI version=AFNI_21.1.00 (Nov  3 2022) [64-bit]
++ Authored by: A cast of thousands
++ WARNING: …
```

:necktie: ACPC align head update 'desc-head_T1w'

---

CPAC/nuisance/nuisance.py

Fixes [`CRASHES v1.8.5/fx-options`](https://drive.google.com/drive/folders/1ww4nIh1SRRWKhd8OB3frgydFPeGo1a2Q) by @amygutierrez 
When applying nuisance correction in template space, sometimes the template-space brain mask is slightly misaligned with the template-space data (for example, the mask's `3dinfo` would show
```
R-to-L extent:   -94.045 [R] -to-    95.045 [L] -step-     3.438 mm [ 56 voxels]
A-to-P extent:   -94.954 [A] -to-   131.954 [P] -step-     3.438 mm [ 67 voxels]
I-to-S extent:   -77.700 [I] -to-   112.700 [S] -step-     3.400 mm [ 57 voxels]
```
while the timeseries `3dinfo` would show
```
R-to-L extent:   -96.028 [R] -to-    96.500 [L] -step-     3.438 mm [ 57 voxels]
A-to-P extent:   -97.846 [A] -to-   132.500 [P] -step-     3.438 mm [ 68 voxels]
I-to-S extent: …
```

👔 `3dresample` template-space brain mask with resampled data

---

CHANGELOG.md
CPAC/anat_preproc/anat_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_abcd-options.yml
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_ccs-options.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/utils/configuration/configuration.py
CPAC/utils/configuration/yaml_template.py

Fixes #1861 by @sgiavasis
- Moves Freesurfer data ingress to the data configuration YAML file.
- It is now under `anat:`, as the key `freesurfer_dir:`
- Splits the existing Freesurfer recon-all post-proc/conversion nodes into their own separate node block.
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```

Freesurfer directory ingress overhaul

---

CPAC/anat_preproc/anat_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/utils/docs.py
CPAC/utils/monitoring/__init__.py
CPAC/utils/monitoring/config.py
dev/docker_data/run.py

Related to #1862 by @sgiavasis & #1865 by @shnizzedy 
1. Catches various potential points of failure when provided a `freesurfer_dir` in a data config but not a pipeline config that uses FreeSurfer outputs
1. Throws a warning at the point of failure
1. Repeats that warning at the end of `pypeline.log`
* Checks for all required resources and throws the warning if we have 'freesurfer-subject-dir' but are missing any others https://github.com/FCP-INDI/C-PAC/blob/d48a4716d5467433c18278b959e5245610402c69/CPAC/anat_preproc/anat_preproc.py#L2570-L2577
* Updates this print statement https://github.com/FCP-INDI/C-PAC/blob/af2d7f160d29129ef8ef4b9546734404139c7715/dev/docker_data/run.py#L806-L809 to a `logger.info` https://github.com/FCP-INDI/C-PAC/blob/c5b6f0dc34d2a79631ed5b1acd0d417f941d88f4/dev/do …

🥅 Handle having `freesurfer_dir` but no FreeSurfer options

---

CPAC/surface/fMRISurface/SubcorticalProcessing.sh

Fixes abcd-options [crash](https://drive.google.com/drive/u/0/folders/1VSQjZ0-hlaF91_NvLMEN5gDIalvMGnpB) in post_freesurfer node. 
Crash states: 
```
subprocess.CalledProcessError: Command '['bash', '/code/CPAC/surface/fMRISurface/run.sh', '--post_freesurfer_folder', '/ocean/projects/med220004p/agutierr/reg_test_1.8.5/all_pipelines_2/abcd-options/KKI/working/pipeline_abcd-options-seed/cpac_1019436_1/post_freesurfer_496', '--subject', '1019436_1', '--fmri', '/ocean/projects/med220004p/agutierr/reg_test_1.8.5/all_pipelines_2/abcd-options/KKI/working/pipeline_abcd-options-seed/cpac_1019436_1/_scan_rest_acq-1_run-1/extract_func_brain_250/vol0000_warp_merged_maths.nii.gz', '--scout', '/ocean/projects/med220004p/agutierr/reg_test_1.8.5/all_pipelines_2/abcd-options/KKI/working/pipeline_abcd-optio …
```

abcd-options postfreesurfer /tmp directory fix 

---

.github/Dockerfiles/FSL.5.0.10-bionic.Dockerfile

Fixes 
```Python
FileNotFoundError: File /usr/share/fsl/5.0/data/standard/tissuepriors/2mm/avg152T1_csf_bin.nii.gz does not exist!
```
by @tergeorge 
Fixes packaging error where templates were being hoisted one directory in ABCD-HCP variant FSL image
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```

📦️ Fix path to tissuepriors in ABCD-HCP variant

---

.github/Dockerfiles/FSL.5.0.10-bionic.Dockerfile
.github/Dockerfiles/base-ABCD-HCP.Dockerfile

Continues #1894 by @shnizzedy & #1896 by @tergeorge 
Gets more specific in copying resources (removes `*` that was hoisting some files)

📦️ Fix FSL resource paths for ABCD-HCP variant image

---

.github/Dockerfiles/base-ABCD-HCP.Dockerfile

Related to
> Use of apt-key is deprecated, except for the use of apt-key del in maintainer scripts to remove existing keys from the main keyring. If such usage of apt-key is desired the additional installation of the GNU Privacy Guard suite (packaged in gnupg) is required.
― <a href="https://manpages.debian.org/testing/apt/apt-key.8.en.html#:~:text=Use%20of%20apt%2Dkey%20is,packaged%20in%20gnupg)%20is%20required."><code>man apt-key</code></a>
* Updates the `connectome-workbench` install command to skip checking the key / signature
* Also reverts f09ff0c8640b4e8204e2f9ce6b0dc272d8878728
```BASH
% docker run --rm -it --entrypoint /bin/bash  ghcr.io/fcp-indi/c-pac:feature_surface_derivatives-wb_command-ABCD-HCP
/usr/share/fsl/5.0/data/standard/tissuepriors
├── 2mm
│   ├── …
```

📦️ Restore `wb_command` installation in ABCD-HCP variant image

---

CPAC/nuisance/tests/utils/test_compcor.py
CPAC/nuisance/utils/compcor.py

Refactor `CPAC.nuisance.utils.compcor.TR_string_to_float`:
- Added documentation
- Added input validation
- Better error reporting
- More explicit logic
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```

Refactor TR_string_to_float

---

CPAC/pipeline/cpac_pipeline.py

Don't run system dependency checks when using `test_config`.
This allows workflow testing and debugging locally without having the system dependencies installed.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon …
```

Don't check system dependencies with test_config

---

CHANGELOG.md
CPAC/__main__.py
CPAC/info.py
CPAC/utils/versioning/dependencies.py
dev/circleci_data/test_external_utils.py
dev/docker_data/run.py
requirements.txt

Fixes #1956 by @shnizzedy
- Makes standardized commands like `data-config` backwards compatible by accepting underscores in place of dashes like `data_config`
- Adds dash'd versions for underscore'd options/arguments (e.g., `--output-dir` now works in place of `--output_dir`) and choices (e.g., `test-config` now works in place of `test_config`)
- The only option where dashes and underscores should still not be interchangeable after this PR is `opt_out` won't work in place of `opt-out` of `--tracking-opt-out`/`--tracking_opt-out` because that dash is semantic, not just delimiting
- For commands, uses [`click-aliases`](https://pypi.org/project/click-aliases/1.0.1/) library to specify aliases without overriding the canonical names
- For arguments, just preprended the dash-delimited …

👽 Update CLI to accept dashes and underscores where appropriate

---

CPAC/resources/configs/pipeline_config_abcd-options.yml
CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml
CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_ccs-options.yml
CPAC/resources/configs/pipeline_config_default-deprecated.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/resources/configs/pipeline_config_fmriprep-options.yml
CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
CPAC/resources/configs/pipeline_config_monkey.yml
CPAC/resources/configs/pipeline_config_ndmg.yml
CPAC/resources/configs/pipeline_config_regtest-1.yml
CPAC/resources/configs/pipeline_config_regtest-2.yml
CPAC/resources/configs/pipeline_config_regtest-3.yml
CPAC/resources/configs/pipeline_config_regtest-4.yml
CPAC/resources/configs/pipeline_config_rodent.yml

Fixes bug in develop where `bold_masking` doesn't run with any preconfigs. The new `func_preproc` switches were set to 'off' in `pipeline_config_blank`, so they weren't running in any of the other preconfigs. I set the switches to 'on' in develop so that the other preconfigs will be updated and those steps will run.
Ran `default` and `abcd-options` pipelines which verified that the crashes in the smoke tests are fixed.
<details>
```
Version 1.1
Suite D4700
Developer's Certificate …
```

🔧 Fix bold_mask crash

---

CPAC/pipeline/check_outputs.py

Add crash tip info box after missing outputs message.
<details>
```
Version 1.1
Suite D4700
license and I have …
```

📦 Add tip info-box after missing output crash

---

CPAC/aroma/aroma.py

The input for the fsl.BET() brain extraction function is a functional image, but only the first volume is required. This function used to automatically grab the first volume, but this feature is now deprecated. I added a [flag](https://nipype.readthedocs.io/en/0.12.0/interfaces/generated/nipype.interfaces.fsl.preprocess.html#:~:text=functional%3A%20(a%20boolean)%0A%20%20%20%20%20%20%20%20apply%20to%204D%20fMRI%20data%0A%20%20%20%20%20%20%20%20flag%3A%20%2DF%0A%20%20%20%20%20%20%20%20mutually_exclusive%3A%20functional%2C%20reduce_bias%2C%20robust%2C%20padding%2C%0A%20%20%20%20%20%20%20%20%20remove_eyes%2C%20surfaces%2C%20t2_guided) that indicates a 4D input and prevents this crash.
I re-ran the benchmark-FNIRT pipeline, which was where I first saw this error, and it completed without …

:triangular_flag_on_post: Add flag to specify functional input

---

CHANGELOG.md
CPAC/generate_motion_statistics/generate_motion_statistics.py
CPAC/pipeline/utils.py
CPAC/utils/interfaces/function/function.py
CPAC/utils/typing.py

Nipype long predates Python support for type hinting, and the way [`Function`](https://github.com/nipy/nipype/blob/71411b0ba6c413190f64e15292e0cab79840087f/nipype/interfaces/utility/wrappers.py#L28-L159) nodes are handled, type hints only work if the types are builtin or defined in the same file that the `Function` node is called from or if the necessary `import` statements are provided in the `Function(…, imports=)` constructor.
* Use string annotations instead of type annotations for anything that's not built-in
* Don't use type annotations
I discovered this behavior when I was testing changes for #1989. The final changes don't need this decorator, but I think it's nice to future developers to supply type hints where we can.
This PR adds a `@sig_imports` decorator to supply the `import` …

🎨 Accomodate type hinting for `Function` node functions

---

.github/Dockerfiles/Ubuntu.jammy-non-free.Dockerfile
CPAC/surface/tests/test_installation.py
CPAC/utils/tests/test_utils.py

Fixes https://cmi-cnl.slack.com/archives/GC8KKE490/p1693505192148309?thread_ts=1693325531.117369&cid=GC8KKE490 by @nx10 
Fixes https://cmi-cnl.slack.com/archives/GC8KKE490/p1693505884160539?thread_ts=1693325531.117369&cid=GC8KKE490 by @e-kenneally 
Fixes #1971 by @shnizzedy
Fixes #1981 by @shnizzedy
Installs `xvfb` in Jammy base OS image.
#1981 moved the Python wrapper installation into C-PAC's install requirements, but that doesn't install the core package.
https://github.com/FCP-INDI/C-PAC/blob/ef5db25fb1b3c1a1fbe3ab517d59763034794bfe/CPAC/utils/tests/test_utils.py#L26-L48 https://github.com/FCP-INDI/C-PAC/blob/ef5db25fb1b3c1a1fbe3ab517d59763034794bfe/CPAC/utils/tests/test_utils.py#L72-L75
<details>
``` …
```

➕ Install `xvfb` in Jammy image

---

CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py

Follow-up to 676705c by @e-kenneally
Fixes af72ff8 by @sgiavasis 
Fixes #1952 by @e-kenneally 
Smoke tests are failing in current `develop` after merging #1952 because, for example,
```Python
bool({'run': False,
'Regressors': {'Name': 'default', 'Columns': ['global_signal']}
}) == True
```
and https://github.com/FCP-INDI/C-PAC/blob/2fb9d13c997c9509a04ce9938f0492409bd63403/CPAC/pipeline/cpac_pipeline.py#L1315-L1320 is checking `cfg.nuisance_corrections['2-nuisance_regression']['ingress_regressors']` which includes dictionary values like that.
This PR: 
1. Adds `'run'` to https://github.com/FCP-INDI/C-PAC/blob/3a2a06ae90332c8685812d2e8e7e9946db76b8f4/CPAC/pipeline/schema.py#L1160-L1161
2. Moves the check from pipeline building to schema validation (so the check happens sooner)
3. Changes …

♻️ Move mutual-exclusivity check to schema validation

---

CPAC/func_preproc/func_preproc.py

Fixes 
> ```Python
> LookupError: When trying to connect node block 'coregistration_prep_fmriprep' to workflow 'cpac_sub-NDARINV2VY7YYNW_ses-baselineYear1Arm1' after node block 'func_normalize': 
> 
> [!] C-PAC says: None of the listed resources in the node block being connected exist in the resource pool.
> 
> Resources:
> ['desc-ref_bold']
> ```
for
```YAML
functional_preproc:
func_masking:
using:
- CCS_Anatomical_Refined
registration_workflows:
functional_registration:
coregistration:
func_input_prep:
input:
- fmriprep_reference
```
by @nx10 & @e-kenneally on Slack
Updates the BOLD resource coming out of the `bold_mask_ccs` NodeBlock to be interchangeable with the BOLD resource coming out of the `bold_mask_fsl_afni` NodeBlock. (The BOLD resource coming out of `bold_mask_ccs` is not …

👔 Make CCS & fMRIPrep BOLD masking steps interchangeable

---

CPAC/pipeline/engine.py
CPAC/utils/typing.py

Related to #2011 by @shnizzedy
Simplified https://github.com/FCP-INDI/C-PAC/blob/dd95a760b8e237bf4274e8e356197498bc28ea96/CPAC/pipeline/engine.py#L335-L378 into https://github.com/FCP-INDI/C-PAC/blob/330f317e72b9bc187badb804ee7aeeff72318c5e/CPAC/pipeline/engine.py#L339-L370 and adds typehints to the method's signature
* This changes one bit of logic here. Before this PR, if a list is passed as `resource` to `ResourcePool.get`, any `pipe_idx` passed to the method is ignored, but if a string is passed, `pipe_idx` is used. I.e.,
| `ResourcePool.get(resource=resource, pipe_idx=pipe_idx)` returns | before | after |
|---|---|---|
| `if isinstance(resource, list)` | `self.rpool[label]` | `self.rpool[label][pipe_idx]`  |
| `if isinstance(resource, str)` | `self.rpool[label][pipe_idx]` | …

🎨 DRY `ResourcePool.get`

---

.github/workflows/smoke_test_participant.yml
CPAC/func_preproc/func_preproc.py
CPAC/nuisance/nuisance.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/engine.py
CPAC/resources/configs/pipeline_config_abcd-options.yml
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_ccs-options.yml
CPAC/resources/configs/pipeline_config_fmriprep-ingress.yml
CPAC/resources/configs/pipeline_config_fmriprep-options.yml
CPAC/utils/typing.py

- Fixes 
```Python
TypeError: string indices must be integers
```
in https://github.com/FCP-INDI/C-PAC/actions/runs/6669328783/job/18127204189
- Fixes
```Python
TypeError: cannot unpack non-iterable NoneType object
```
in https://github.com/FCP-INDI/C-PAC/actions/runs/6669328783/job/18127204189
- Fixes
> Where it seems to try to look up the error message itself in a list?
by @nx10 on Slack
Dashes and spaces in the regressor names were causing problems in the regressors downstream from forked filters, so I updated the regressor naming to only include alphanumeric characters and no-more-than-one-in-a-row underscores, which renamed some regressors in some preconfigs to names including underscores, which doesn't play well with https://github.com/FCP-INDI/C-PAC/blob/7ff4a9341eb0784443bef1680cae …

🐛 Fix some bugs found via 1.8.6-dev smoke tests

---

CHANGELOG.md
CPAC/utils/configuration/configuration.py
CPAC/utils/configuration/yaml_template.py
CPAC/utils/tests/configs/__init__.py
CPAC/utils/tests/test_yaml.py
CPAC/utils/utils.py
dev/docker_data/run.py

Fixes [`FileNotFoundError: [Errno 2] No such file or directory: '/code/CPAC/resources/configs/pipeline_config_/configs/pipeline_config_cpac_1.8.5_fromPhoebeNoDeriviativesNative.yml.yml'`](https://tinyurl.com/cmicnlslack420349) by [@Shinwon Park](https://cmi-cnl.slack.com/team/U05CG6L2RB3)
Consolidates https://github.com/FCP-INDI/C-PAC/blob/ecfc583ac03a57fed185fd5028c27d378d08fa8f/CPAC/utils/utils.py#L1518-L1542 and https://github.com/FCP-INDI/C-PAC/blob/ecfc583ac03a57fed185fd5028c27d378d08fa8f/CPAC/utils/configuration/configuration.py#L606-L625 into https://github.com/FCP-INDI/C-PAC/blob/907fab5e0e6e4efda0046ee04ddc4a74d07b170b/CPAC/utils/configuration/configuration.py#L620-L647 so preconfiguration loading is handled consistently everywhere and updates the relevant function calls. …

🐛 Fix parsing `FROM: /filepath`

---

CHANGELOG.md
CPAC/nuisance/nuisance.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/resources/configs/pipeline_config_fmriprep-ingress.yml
CPAC/resources/configs/pipeline_config_fmriprep-options.yml
CPAC/utils/datatypes.py

Fixes #2018 by @shnizzedy & [@Shinwon Park](https://cmi-cnl.slack.com/team/U05CG6L2RB3)
Makes nuisance regression space non-forkable.
At schema validation, ensures only one space is chosen.
- Ran `test_config` with each of
- ```YAML
space: ['native', 'template']
```
- ```YAML
space: ['native']
```
- ```YAML
space: ['template']
```
and got expected results (validation error, success, success, respectively)
- https://github.com/FCP-INDI/C-PAC/blob/3eae380c875d587e38359dbbb75c719e91ffdc70/CPAC/utils/datatypes.py#L9-L16
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```

👔 Make nuisance regression space non-forkable

---

CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py
CPAC/unet/_torch.py
CPAC/unet/tests/test_torch.py
CPAC/utils/configuration/configuration.py

Fixes 
```Python
Installing collected packages: nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cublas-cu11, nvidia-cudnn-cu11, torch, torchvision
ERROR: Could not install packages due to an OSError: [Errno 30] Read-only file system: '/home/c-pac_user/.local'
```
by @e-kenneally [on Slack](https://cmi-cnl.slack.com/archives/C065W7YJ4V9/p1700146457157509)
- Nothing different if the container is writable
```mermaid
graph TD;
P[set '$CPAC_WORKDIR' when loading pipeline config] --> A
A{container writable?} -->|yes| B[nothing different] --> Y
A -->|no| C[try to install torch in '$CPAC_WORKDIR/.local'] --> D{success} -->|yes| Y[torch installed]
D -->|no| E[set 'CPAC_WORKDIR = $PWD'] --> F[install torch in '$CPAC_WORKDIR/.local'] --> Y
Y --> R[run to end of workflow or graceful crash] …
```

🐛 Install `torch` dynamically in a read-only container

---

CPAC/pipeline/__init__.py
CPAC/pipeline/nipype_pipeline_engine/monkeypatch.py

Fixes #1955 by @amygutierrez
- Since Nipype version ~1.8.x Nipype emits many (!) `.proc-*` to the _user_ working directory (wherever the user started nipype from, instead of _nipype_ working directory node subdirectories)
@shnizzedy 's exhaustive internal writedown 🕵️
> C-PAC and fMRIPrep both hit the issue upgrading from nipype 1.5.x to 1.8.x; I think [this](https://github.com/nipy/nipype/blob/071523a5069b52689ed27f995f1e2bea5b6e0402/nipype/interfaces/base/core.py#L370) chdir that used to be before [initializing the ResourceMonitor](https://github.com/nipy/nipype/blob/071523a5069b52689ed27f995f1e2bea5b6e0402/nipype/interfaces/base/core.py#L410) led to [this relative path](https://github.com/nipy/nipype/blob/3b505327f412a2c4215d0763f932d0eac6e3a11b/nipype/utils/profiler.py#L59) being …

Prevent Nipype from emitting .proc-* files to user working dir Fix #1955 

---

CPAC/pipeline/engine.py
CPAC/pipeline/utils.py

Co-Authored by: jon.clucas@childmind.org 
The name of the regressor strategy used wasn't showing up in the output directory filenames because the method used to grab the regressor strategy name wasn't consistently effective. @shnizzedy proposed this new method to grab the last segment of the value under `CpacVariant` in the JSON sidecar. 
After the naming was fixed, the C-PAC engine was still registering the different nuisance regressor strategies as forks in the pipeline and adding numbers to the filenames. The problem stemmed from when we re-named 'regressors' to 'desc-confounds_timeseries' but forgot to update the wording in this section.
I ran the full regression testing suite on these changes and everything went smoothly.
<details> …

Fix nuisance regression file naming issue

---

CPAC/pipeline/cpac_pipeline.py

Option-forked nodeblock lists only report the name of the last nodeblock in the list when a missing resource is reported.
E.g.:
Users will see
```sh
LookupError: When trying to connect one of the node blocks 'bold_mask_ccs' to workflow 'cpac_sub-01_ses-1' after node block 'motion_estimate_filter': 
[!] C-PAC says: None of the listed resources are in the resource pool:
['space-template_desc-T1w_mask']
```
while the nodeblock not necessarily has anything to do with the missing resource.
Now they will see:
```sh
LookupError: When trying to connect one of the node blocks ['bold_mask_afni', 'bold_mask_fsl', 'bold_mask_fsl_afni', 'bold_mask_anatomical_refined', 'bold_mask_anatomical_based', 'bold_mask_anatomical_resampled', 'bold_mask_ccs'] to workflow 'cpac_sub-01_ses-1' after node block …
```

Option-forked nodeblock missing resource name reporting

---

CPAC/anat_preproc/anat_preproc.py
CPAC/anat_preproc/utils.py
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/resources/cpac_outputs.tsv

Fixes #1928 by @birajstha 
This PR further expands the work of former cpac developer @tergeorge, by addressing the bug on implementation of RobustFOV.
RobustFOV crops the Nifti Image and hence when BET generates the mask, the mask doesnot match the dimension of the original resampled image thus giving error in "3Dcalc" down the pipeline.
Tested on few (4-5) sample datasets with and without neck regions in the image where it performed as expected.
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```

fslrobustfov with padding inorder to remove neck regions in the fsl-bet skull stripped image

---

CPAC/pipeline/nipype_pipeline_engine/plugins/cpac_nipype_custom.py

```Python
The following nodes are estimated to exceed the total amount of memory available (150.00GB): 
aCompCor_cosine_filter: 151.0 GB
```
by @birajstha 
The throttling introduced in #2075 didn't account for C-PAC + Nipype overhead estimates being added to the node estimate. This change subtracts the overhead estimate from the throttle estimate so the full estimate will include the overhead exactly once.
<details>
```
Version 1.1
Suite D4700 …
```

🐛 Don't include overhead in throttled node allocation

---

.pre-commit-config.yaml
CPAC/pipeline/schema.py
CPAC/resources/configs/pipeline_config_regtest-4.yml
CPAC/utils/configuration/configuration.py
CPAC/utils/configuration/yaml_template.py

Fixes #2046 by @shnizzedy 
In reviewing https://github.com/FCP-INDI/C-PAC/pull/1933#discussion_r1496169967, I noticed we (I) lost the YAML comment autoupdates in #2046. This PR restores that functionality, but also moves it from the CI to a pre-commit hook.
A couple changes were necessary here:
1. With `torch` moved out of the pre-installed packages, the pipeline config validator checks that we have it or can install it if `unet` is selected https://github.com/FCP-INDI/C-PAC/blob/16320b95f67dbbcb8eb4a1e73cc99182d5e769c0/CPAC/pipeline/schema.py#L1191-L1201
2. `$FSLDIR` wasn't/isn't set in the CI images, but likely will be on developers' machines.
To get over both of these hurdles, this PR adds https://github.com/FCP-INDI/C-PAC/blob/16320b95f67dbbcb8eb4a1e73cc99182d5e769c0/CPAC/utils/configu …

🧑‍💻 Move YAML comment updater to pre-commit hook

---

CPAC/nuisance/utils/utils.py

Fixes https://github.com/FCP-INDI/C-PAC/pull/2059#discussion_r1472295222 by @shnizzedy with https://github.com/FCP-INDI/C-PAC/pull/2059#discussion_r1483106483 by @nx10 
> https://github.com/FCP-INDI/C-PAC/blob/85737a19957a212586de173fb18d5ffe0ad6ed40/CPAC/nuisance/utils/utils.py#L639-L640
> It hasn't seemed to cause a problem, but I don't understand why this case would return None instead of pipeline_resource_pool or {}
> If no one knows you could turn it into an error? Maybe it just never happens?
This just changes that `return None` into a `raise LookupError`
<details>
```
Version 1.1
Suite D4700 …
```

🥅 Raise an error instead of returning `None` where a dict is expected

---

.github/Dockerfiles/C-PAC.develop-ABCD-HCP-bionic.Dockerfile
.github/Dockerfiles/C-PAC.develop-fMRIPrep-LTS-xenial.Dockerfile
.github/Dockerfiles/C-PAC.develop-jammy.Dockerfile
.github/Dockerfiles/C-PAC.develop-lite-jammy.Dockerfile
CHANGELOG.md
CPAC/info.py
CPAC/utils/versioning/dependencies.py
Dockerfile
dev/docker_data/unpinned_requirements.txt
pyproject.toml
requirements.txt
setup.py
variant-ABCD-HCP.Dockerfile
variant-fMRIPrep-LTS.Dockerfile
variant-lite.Dockerfile

Related to [:snake: PEP 518 – Specifying Minimum Build System Requirements for Python Projects](https://peps.python.org/pep-0518/)
Related to [:octocat:/childmindresearch/nodeblock-testing](https://github.com/childmindresearch/nodeblock-testing)
1. Adds a `pyproject.toml` file with just a license and build system requirements https://github.com/FCP-INDI/C-PAC/blob/3f23711275ebcb5de6ca99ed338c26d6ea230f42/pyproject.toml#L17-L19
2. Prepends the source path to `sys.path` https://github.com/FCP-INDI/C-PAC/blob/3f23711275ebcb5de6ca99ed338c26d6ea230f42/setup.py#L50-L51 to be able to import from `CPAC.info` at build-time https://github.com/FCP-INDI/C-PAC/blob/3f23711275ebcb5de6ca99ed338c26d6ea230f42/setup.py#L52-L67
3. Switches the PyPEER dependency from …

📦️ PEP 518: Set `[build-system]` in `pyproject.toml`

---

.github/Dockerfiles/Ubuntu.jammy-non-free.Dockerfile
CHANGELOG.md
CPAC/utils/tests/test_bids_utils.py
CPAC/utils/versioning/dependencies.py
pyproject.toml
requirements.txt

Fixes #2110 by @shnizzedy
Related to [[comment]](https://neurostars.org/t/running-an-older-version-of-c-pac-v1-3-0/29178/4?u=shnizzedy) by @shnizzedy (response to [<img src="https://neurostars.org/uploads/default/optimized/1X/eadd889a719a1e6370fbe086d518eafd6cd4586c_2_32x32.png" alt="Neurostars" width="14px"/> Running an older version of C-PAC (V1.3.0)](https://neurostars.org/t/running-an-older-version-of-c-pac-v1-3-0/29178) by [@Ammar_Ibrahim](https://neurostars.org/u/Ammar_Ibrahim))
> In looking into the issue, I discovered that we inadvertently removed the bids-validator CLI, so trying to run with the BIDS validator in versions 1.8.6 and 1.8.7 will fail as well.
― [<img src="https://neurostars.org/uploads/default/optimized/1X/eadd889a719a1e6370fbe086d518eafd6cd4586c_2_32x32.png" …

📦️ Restore `bids-validator` installation in containerized C-PAC images

---

CPAC/__main__.py
CPAC/cwas/tests/test_cwas.py
CPAC/cwas/tests/test_pipeline_cwas.py
CPAC/image_utils/tests/test_smooth.py
CPAC/nuisance/tests/test_utils.py
CPAC/pipeline/check_outputs.py
CPAC/pipeline/test/test_cpac_group_runner.py
CPAC/utils/build_data_config.py
CPAC/utils/monitoring/custom_logging.py
CPAC/utils/ndmg_utils.py
CPAC/utils/tests/test_bids_utils.py
CPAC/utils/tests/test_symlinks.py
CPAC/vmhc/tests/test_vmhc.py

Fixes 
> [lots of the CPAC output messages are printing twice even with verbose turned off](https://cmi-cnl.slack.com/archives/C065W7YJ4V9/p1720811602525219)
by @e-kenneally 
Two logging handlers were often each handling each log message. With this PR, each logger will have either one nipype handler that streams and writes to file as configured or at most one each stream handler and file handler to handle streaming to terminal and writing to file, respectively.
We were initializing non-nipype loggers with
```Python
basicConfig(format="%(message)s", level=INFO)
```
but that was setting a _global_ handler, which was also applying to nipype loggers.
With this PR, we just add a [StreamHandler](docs.python.org/3.11/library/logging.handlers#logging.StreamHandler) if a …

🐛 Fix double-logging

---

CPAC/utils/interfaces/netcorr.py

Related to Slack thread [`p1731021618662679`](https://cmi-cnl.slack.com/archives/C065W7YJ4V9/p1731021618662679?thread_ts=1730737939.657969&cid=C065W7YJ4V9)…[`p1731107909945459`](https://cmi-cnl.slack.com/archives/C065W7YJ4V9/p1731107909945459?thread_ts=1730737939.657969&cid=C065W7YJ4V9) by @birajstha, @tamsinrogers, @sgiavasis & @shnizzedy 
Related to https://github.com/nipy/nipype/issues/3696 by @shnizzedy
Related to https://github.com/nipy/nipype/issues/3697 by @shnizzedy
Includes the fix from https://github.com/nipy/nipype/pull/3697 in C-PAC without waiting for the fix to be released in Nipype and then updating the Nipype version in the C-PAC container.
> ### List of changes proposed in this PR (pull-request)
> 
> 
> * https://github.com/nipy/nipype/blob/237a9a7ca244ca87916e1f9c5bd73c3f …

🐛 Patch `NetCorr._list_outputs`

---

CPAC/pipeline/engine.py

Fixes 
```Python
[...]
File "/code/CPAC/pipeline/engine.py", line 1361, in gather_pipes
wf.connect(node, out, nii_name, "in_file")
File "/usr/share/fsl/6.0/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 161, in connect
self._check_nodes(newnodes)
File "/usr/share/fsl/6.0/lib/python3.10/site-packages/nipype/pipeline/engine/workflows.py", line 761, in _check_nodes
if node.name in node_names:
AttributeError: 'NoneType' object has no attribute 'name'
```
by @tamsinrogers
When this `node` https://github.com/FCP-INDI/C-PAC/blob/fc97ae86a0043f410fcd07a426351d2f5f16acdb/CPAC/pipeline/engine.py#L1359 is `None`, instead of passing that `None` along to make Nipype throw up 🤮, raise a `FileNotFoundError` and tell the user which resource is …

🥅 Alert missing resource trying to output

---

.github/dependabot.yaml
.github/workflows/build_C-PAC.yml
.github/workflows/build_and_test.yml
.github/workflows/delete_images.yml
.github/workflows/deploy_to_Docker_Hub.yml
.github/workflows/on_push.yml
.github/workflows/regression_test_full.yml
.github/workflows/regression_test_lite.yml
.github/workflows/smoke_test_participant.yml

Fixes
> [Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/](https://github.com/FCP-INDI/C-PAC/actions/runs/13168636290)
by @birajstha 
All we need to do to resolve the issue is to update all the lines like https://github.com/FCP-INDI/C-PAC/blob/3ffec0970625e13906a06fb61d94329f792b3f80/.github/workflows/smoke_test_participant.yml#L107 to https://github.com/FCP-INDI/C-PAC/blob/7646484553204ed829e6a48c7af3f57829d57b6f/.github/workflows/smoke_test_participant.yml#L107 but this PR also:
* Sets up Dependabot to check for these kinds of deprecations weekly and open PRs automatically when we need to upgrade GH Actions …

👷 🔧 Configure and run Dependabot

---

.github/workflows/smoke_test_participant.yml
CPAC/anat_preproc/anat_preproc.py

Fixes #2184 by @birajstha
Restores https://github.com/FCP-INDI/C-PAC/blob/7246e449ae56ba116203bead402b95fa84629d17/CPAC/anat_preproc/anat_preproc.py#L2767-L2782 ([removed in #2184](https://github.com/FCP-INDI/C-PAC/pull/2184/files#diff-b8ed898622a28e32db94baa4030d462bfab350311f4656b04153d6426dff8d43L2767-L2782)) to the outputs of https://github.com/FCP-INDI/C-PAC/blob/1771f7be37619bee50d9ac548ccdacc5f5bfe04c/CPAC/anat_preproc/anat_preproc.py#L2895-L2896
* `"freesurfer_reconall"` includes all outputs of `"freesurfer_abcd_preproc"`, so when these outputs were removed from `"freesurfer_abcd_preproc"`, they were also removed from `"freesurfer_reconall"`, which led to some failing smoke tests (see [Screenshots](#screenshots) for an example).
* Also replaces the setup-conda GitHub Workflows …

🐛 Restore outputs removed from "freesurfer_abcd_preproc" to "freesurfer_reconall"

---

.github/Dockerfiles/AFNI.23.3.09-jammy.Dockerfile
.github/Dockerfiles/ANTs.2.4.3-jammy.Dockerfile
.github/Dockerfiles/C-PAC.develop-jammy.Dockerfile
.github/Dockerfiles/C-PAC.develop-lite-jammy.Dockerfile
.github/Dockerfiles/FSL.6.0.6.5-jammy.Dockerfile
.github/Dockerfiles/FSL.data.Dockerfile
.github/Dockerfiles/FreeSurfer.6.0.0-min.neurodocker-jammy.Dockerfile
.github/Dockerfiles/ICA-AROMA.0.4.4-beta-jammy.Dockerfile
.github/Dockerfiles/Ubuntu.jammy-non-free.Dockerfile
.github/Dockerfiles/base-lite.Dockerfile
.github/Dockerfiles/base-standard.Dockerfile
.github/Dockerfiles/c3d.1.0.0-jammy.Dockerfile
.github/Dockerfiles/connectome-workbench.1.5.0.neurodebian-jammy.Dockerfile
.github/Dockerfiles/neuroparc.1.0-human-bionic.Dockerfile
Dockerfile
variant-lite.Dockerfile

Related to [dockerdocs: LegacyKeyValueFormat](https://docs.docker.com/reference/build-checks/legacy-key-value-format/)
Replaces regex
```regex
(LABEL [a-zA-Z\.]*)( )
```
with
```regex
$1=
```
in all the Dockerfiles (i.e., every `LABEL key value` becomes `LABEL key=value`).
<details>
```
Version 1.1
Suite D4700
have the …
```

👽️ Update Dockerfile `LABEL`s re: deprecated `LegacyKeyValueFormat`

---

CHANGELOG.md
CPAC/func_preproc/func_preproc.py
CPAC/pipeline/cpac_pipeline.py
CPAC/pipeline/schema.py
CPAC/registration/registration.py
CPAC/resources/configs/pipeline_config_abcd-options.yml
CPAC/resources/configs/pipeline_config_blank.yml
CPAC/resources/configs/pipeline_config_default.yml

Fixes #[2174](https://github.com/FCP-INDI/C-PAC/issues/2174) by @sgiavasis 
Refactors `sbref` generation by updating BOLD input selection to improve clarity and flexibility. Replaces `desc-brain_bold` with `desc-preproc_bold`, introduces `desc-head_bold` as a bookmark resource, and adds an option to `mask sbref` in the config.
- Changed the input to `desc-preproc_bold` 
- Removed the whole-head input `desc-head_bold` and `bold` 
- Created `desc-head_bold` as a bookmark resource at `bold_masking` nodeblock
- Added `mask_sbref` switch in the config as an option.
- 
Try running the custom pipeline config as mentioned below
```YAML
registration_workflows:
functional_registration:
func_input_prep:
input: [Selected_Functional_Volume]
functional_preproc:
func_masking: …
```

✨Introduced desc-head_bold and changed sbref generating nodeblock

---

CPAC/registration/registration.py

Fixes [failing smoke tests](https://github.com/FCP-INDI/C-PAC/actions/runs/14110790786)
Related to #2182 by @birajstha 
Related to 20572de by @e-kenneally 
1. Updates one place where resources were being dynamically named `"space-template_desc-T1w_mask"` https://github.com/FCP-INDI/C-PAC/blob/252eed4ab3fd3353868f9061f85b7065dd5ab0c7/CPAC/registration/registration.py#L1604 to `"space-template_desc-brain_mask"` https://github.com/FCP-INDI/C-PAC/blob/e447211689a04ff7f291da5b1c05d97e028373e9/CPAC/registration/registration.py#L1604 re: #2182
2. Adds 5 resources to https://github.com/FCP-INDI/C-PAC/blob/beddfae7c1075823a39905530eb0e84b652909e9/CPAC/registration/registration.py#L2305-L2306 https://github.com/FCP-INDI/C-PAC/blob/beddfae7c1075823a39905530eb0e84b652909e9/CPAC/registration/registrati …

🐛 Update resources to resolve failing smoke tests

---

CHANGELOG.md
CPAC/resources/configs/pipeline_config_abcd-options.yml
CPAC/resources/configs/pipeline_config_abcd-prep.yml
CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml
CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
CPAC/resources/configs/pipeline_config_ccs-options.yml
CPAC/resources/configs/pipeline_config_default-deprecated.yml
CPAC/resources/configs/pipeline_config_default.yml
CPAC/resources/configs/pipeline_config_fmriprep-ingress.yml
CPAC/resources/configs/pipeline_config_fmriprep-options.yml
CPAC/resources/configs/pipeline_config_monkey-ABCD.yml
CPAC/resources/configs/pipeline_config_monkey.yml
CPAC/resources/configs/pipeline_config_ndmg.yml
CPAC/resources/configs/pipeline_config_regtest-1.yml
CPAC/resources/configs/pipeline_config_regtest-2.yml
CPAC/resources/configs/pipeline_config_regtest-3.yml
CPAC/resources/configs/pipeline_config_regtest-4.yml
CPAC/resources/configs/pipeline_config_rodent.yml

* Related to 
> `pipeline_setup.output_directory.quality_control.generate_xcpqc_files` seems to be true by default for RBC, false for fmriPrep, ABCD and CCS
by @nx10 [on <img alt="Slack" src="https://github.com/user-attachments/assets/33ead9cf-02c7-4304-b830-124ee8f8e7e9" height="12px">](https://cmi-cnl.slack.com/archives/C06DP5JLK9R/p1742399472065999?thread_ts=1742251320.388849&cid=C06DP5JLK9R)
* Related to conversation in [2025-03-27 <img alt="Teams meeting" src="https://github.com/user-attachments/assets/fede92ee-0d77-4c08-b48a-c066c59cbe69"> DAIR Topic Focus: Pipeline, Platforms & Sustainability](https://teams.microsoft.com/l/meetingrecap?driveId=b%21QofO9yx4CUqXWTzFrVX9VIoJ7c9A9RRFuHvA_oBee-vfTV_0E9K-TpX6W5ZAUyo9&driveItemId=01MCKYGNMIFVJBIKJHZJHZNXOYSMW2U2CE&sitePath=https%3A%2F%2Fch …

🔧 Turn on XCP-QC by default in preconfigs

---

CPAC/anat_preproc/utils.py
CPAC/pipeline/engine.py
CPAC/utils/utils.py

Fixes #2200 by @birajstha 
related to #2193 by @tamsinrogers 
Alignment issues during applying mask ingressed from Freesurfer outputs.
Resources from [ingress_freesurfer](https://github.com/FCP-INDI/C-PAC/blob/0cf8248c0d6901e9d31d66649b77cdba231560cf/CPAC/pipeline/engine.py#L1965) are skipping reorient and are used directly [like in here.](https://github.com/FCP-INDI/C-PAC/blob/96db8b0b65ab1d5f55fb3b895855af34d72c17e4/CPAC/anat_preproc/anat_preproc.py#L917C1-L943C25)
This causes the files ingressed to have different orientation and is incompatible with rest of the data causing alignment issues such as above.
This PR solves the above issue by aligning the ingressed resources to common orientation.
After the fix
<details>
```
Developer …
```

Freesurfer ingress reorient
