CPAC/nuisance/nuisance.py, CPAC/pipeline/cpac_ga_model_generator.py, CPAC/pipeline/cpac_group_runner.py, CPAC/utils/create_flame_model_files.py, CPAC/utils/extract_data.py, README.md, scripts/cpac_setup.py
I also posted an issue on the forum relating to this change.
=> In case this is useful: Typecasting to avoid bandpass type issue.

CPAC/GUI/resources/html/_sources/install.txt, CPAC/GUI/resources/html/install.html, scripts/cpac_install.sh
This PR contains 2 modifications:
- Remove one step of Ubuntu installation, by setting an output for `wget` command
- Fix libXp Git URL
=> Ubuntu installation

CPAC/EPI_DistCorr/EPI_DistCorr.py, CPAC/GUI/interface/pages/anatomical.py, CPAC/pipeline/cpac_pipeline.py, CPAC/registration/registration.py
Summary of changes:
1. Removed epi_reg from EPI_DistCorr
2. Added to resource pool:
-automask of fieldmap
-wmseg_distortion
3. changed registration.py script to include running FLIRT with fieldmap
4. changed anatomical GUI to include pedir.
=> shifted distortion correction

CPAC/GUI/interface/windows/main_window.py, CPAC/utils/build_data_config.py
=> [Feature] Set default of GUI widgets to pipeline config

CPAC/nuisance/utils.py, CPAC/pipeline/cpac_pipeline.py, CPAC/utils/strategy.py
Resolves the forking schema, to include bandpass into folder name, and fix a forking problem on median angle corr.
=> [FIX] Resolving forks

required_afni_pkgs.txt
Add 3dinfo to allow debugging.
FIxes https://github.com/FCP-INDI/C-PAC/issues/946
=> [ENH] Add 3dinfo to Docker image

dev/docker_data/run.py
Fixes https://github.com/FCP-INDI/C-PAC/issues/894
=> [FIX] Do not override pipeline options

CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/cpac_runner.py, CPAC/utils/ndmg_utils.py, CPAC/utils/strategy.py
It will run the pipeline, but whenever there is an error, it will still delete the working directory if removeWorkDir is enabled.
Fixes #944
=> [ENH] Improve workdir deletion

CPAC/anat_preproc/anat_preproc.py, CPAC/pipeline/cpac_pipeline.py
Fixes #994 
Thanks @nimzodisaster !
=> [FIX] Wrong logic for skullstripping and already skullstripped images

CPAC/GUI/interface/pages/nuisance.py
Fixes https://github.com/FCP-INDI/C-PAC/issues/1009
=> [FIX] Get float values from threshold fields

CPAC/anat_preproc/anat_preproc.py, CPAC/anat_preproc/utils.py, CPAC/pipeline/cpac_pipeline.py, CPAC/resources/configs/pipeline_config_monkey.yml
added AFNI 3dSkullStrip -monkey flag
=> AFNI 3dSkullStrip -monkey flag

CPAC/nuisance/__init__.py, CPAC/nuisance/nuisance.py, CPAC/nuisance/utils/compcor.py, CPAC/pipeline/cpac_pipeline.py, CPAC/seg_preproc/__init__.py
=> Cosinefilter

CPAC/anat_preproc/anat_preproc.py
Fixes #1087 .
It will deoblique and reorient the brain mask before applying it to the anatomical image.
=> [BUGFIX] Brain mask preproc

CPAC/pipeline/cpac_pipeline.py, CPAC/qc/data/index.html, CPAC/qc/utils.py, setup.py
Port my QC to C-PAC. It transverses the QC dir looking for images, and save a list of images to a HTML, that is saved to QC dir on output.
Havent cleaned the old QC functionalities tho.
=> [Feature/Bugfix/Chore] QC pages

CPAC/resources/configs/pipeline_config_template.yml
There are two smoothing method: AFNI or FSL 
I include it in the config file 
`smoothing_method=['FSL']`
=> smoothing method 

CPAC/qc/utils.py
Correct names of rotation and translation plots, which should fix https://github.com/FCP-INDI/C-PAC/issues/1147.
=> Correct names of rotation and translation plots

CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml, CPAC/resources/configs/pipeline_config_monkey.yml, CPAC/resources/configs/pipeline_config_ndmg.yml, CPAC/resources/configs/pipeline_config_preproc.yml, CPAC/resources/configs/pipeline_config_template.yml, dev/docker_data/default_pipeline.yml
Remove duplicate configuration entry seg_csf_use_erosion.
=> Remove duplicate configuration entry

CPAC/qc/utils.py
This should squash that bug (works with toy data), but do we have a real config for which this error occurs? Should we catch and flag arrays that contain infinities?
Resolves #1194
=> ✏️ 🐛 Subset Numpy Array to Exclude Infinite Values Before Histogramming

CPAC/distortion_correction/distortion_correction.py, CPAC/pipeline/cpac_pipeline.py, CPAC/registration/registration.py, CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml, CPAC/resources/configs/pipeline_config_fmriprep-options.yml, CPAC/resources/configs/pipeline_config_monkey.yml, CPAC/resources/configs/pipeline_config_ndmg.yml, CPAC/resources/configs/pipeline_config_preproc.yml, CPAC/utils/bids_utils.py, CPAC/utils/build_data_config.py, CPAC/utils/datasource.py, dev/docker_data/bids_utils.py, dev/docker_data/default_pipeline.yml
CHANGES:
- Changes the expected data configuration schema for field maps. Brings phase difference and phase encoding direction based field maps together under the "fmap" key.
- Fixes issue where phase difference field maps were not making it to distortion correction.
- Changed so that phase difference field map meta-data is pulled in from scan parameter .JSON files (#1056 ).
STILL TODO:
- Fix data configuration generation.
- Needs to properly identify and parse root-level phasediff.json sidecars.
=> [WIP] Fix/fmap ingress

Dockerfile
* https://repo.continuum.io → https://repo.anaconda.com
* 4.7.12.1 :arrow_up: 4.8.2
* `conda update conda`
=> 🚀 Miniconda installer @ 4.8.2; `conda update conda`

CPAC/resources/configs/pipeline_config_fmriprep-options.yml
missing. 1.--metric Mattes  2.--use-estimate-learning-rate-once 1 3.--float 1
=> updated fmriprep-option config

CPAC/utils/build_data_config.py
because [CPAC/resources/configs/pipeline_config_template.yml](https://github.com/FCP-INDI/C-PAC/commit/d206f484f315fcd28be66aec1598bba98a632ad7#diff-3ff3cbe5e3ed6c014625166e8510dd75) no longer exists.
Ref https://fcp-indi.github.io/docs/user/pipeline_config#using-a-text-editor, d206f48
=> 🔨 Point `pipe_config new_template` to /cpac_resources/default_pipeline.yml

CPAC/pipeline/cpac_pipeline.py
To solve https://github.com/FCP-INDI/C-PAC/issues/1273
=> Refactor anat to mni registration

CPAC/pipeline/cpac_pipeline.py
fix https://github.com/FCP-INDI/C-PAC/issues/1300
=> fix csv read error

CPAC/nuisance/utils/__init__.py, CPAC/pipeline/cpac_pipeline.py, Dockerfile, Singularity
=> 🔧 Update linking libGL and libgsl for Singularity builds from Docker images

CPAC/utils/interfaces/datasink.py
Fixes #1260 by @HechengJin0 
At the point where the datasink copies from `src` to `dest`, add a check if they're the same path. Only copy if the paths aren't the same.
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> 🚸 Don't try to copy src to dest if src==dest

CPAC/resources/configs/test_configs/data-test_4-projects_5-subjects.yml, CPAC/resources/configs/test_configs/data-test_5-projects_5-subjects.yml
This PR updates some paths for CBIC data in `test_configs` that did not match the paths on S3.
index.md`).
<details>
```
Version 1.1
Suite D4700
of my …
```
=> 🔧 Fix some CBIC S3 paths

Dockerfile
add ANTSPATH in dockerfile  (used for ants priors based segmentation antsJointLabelFusion.sh)
=> add antspath

Singularity
Fixes #1310 by @shnizzedy
* Removes code from the Singularity recipe that prevents links set up in Dockerfile from linking correctly in Singularity image
To do: update
https://github.com/FCP-INDI/C-PAC/blob/afe6315d1e777e55630dd53b221c1f71c513506a/.circleci/config.yml#L97-L111
to build with Singularity recipe instead of directly from Singularity CLI. This will be included in a PR that updates CircleCI configuration. (This PR is to a point in develop prior to building a Singularity image in 
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
=> Ⓢ Update Singularity recipe to use Dockerfile library links

CPAC/resources/configs/pipeline_config_monkey.yml
monkey preconfig updated based on S3 link
=> update monkey config

CPAC/distortion_correction/distortion_correction.py, CPAC/registration/output_func_to_standard.py
Converted AFNI 3dQWarp to a function node to ensure it properly writes out the Qwarp_PLUS_WARP.nii.gz.
=> Fix the blip Qwarp writing error.

README.md
* Link to latest release notes on docs site (instead of v1.6.0 on GH)
* Add link to CONTRIBUTING.md in developer links section
* Link to versioned docs URLS (the old links redirect, but might as well skip that step)
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
=> ✏️ Update links in README

.circleci/config.yml, Dockerfile, version
Installs libxp while git://anongit.freedesktop.org/xorg/lib/libXp is down
Replaces the install-from-source section for libxp with an apt-based installation from [a third-party repository](https://launchpad.net/~zeehio/+archive/ubuntu/libxp)
- [Build on CircleCI](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/575/workflows/a55e7e6b-120b-41d5-a524-65c6e98f4087/jobs/2975)
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> 📦 Install libxp from zeehio

CPAC/func_preproc/func_preproc.py, CPAC/utils/strategy.py
Fixes https://github.com/FCP-INDI/C-PAC/issues/1371
Fix despike forking
Fix by 1) append despike strategy name; 2) add despike label in strategy.py
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> fix despike forking

CPAC/alff/alff.py, CPAC/anat_preproc/anat_preproc.py, CPAC/cwas/pipeline.py, CPAC/easy_thresh/easy_thresh.py, CPAC/func_preproc/func_preproc.py, CPAC/generate_motion_statistics/generate_motion_statistics.py, CPAC/group_analysis/group_analysis.py, CPAC/median_angle/median_angle.py, CPAC/nuisance/nuisance.py, CPAC/registration/registration.py, CPAC/reho/reho.py, CPAC/sca/sca.py, CPAC/scrubbing/scrubbing.py, CPAC/seg_preproc/seg_preproc.py, CPAC/utils/utils.py, CPAC/vmhc/vmhc.py
Fixes https://github.com/FCP-INDI/fcp-indi.github.com/issues/243 by @shnizzedy
Fixes broken workflow graph code in docstrings
| Before | After |
|---|---|
| ![anat_preproc](https://user-images.githubusercontent.com/5974438/96918000-9f3a6480-1477-11eb-98a3-4a0c87267ded.png) | ![anat_preproc](https://user-images.githubusercontent.com/5974438/96924458-ac0f8600-1480-11eb-8f4d-1d336cc36387.png) |
| ![func_preproc](https://user-images.githubusercontent.com/5974438/96918089-c2651400-1477-11eb-83f0-19f6013f9d25.png) | ![func_preproc](https://user-images.githubusercontent.com/5974438/96918154-de68b580-1477-11eb-8fa4-ceb69af0e993.png) |
| ![seg_preproc (1/2)](https://user-images.githubusercontent.com/5974438/96918269-0d7f2700-1478-11eb-9674-55d1c62097d6.png) | ![seg_preproc …
=> 📝 Restore broken DOT graphs in docstrings

CPAC/anat_preproc/utils.py, CPAC/network_centrality/network_centrality.py, CPAC/network_centrality/pipeline.py, CPAC/network_centrality/utils.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/cpac_runner.py, CPAC/pipeline/schema.py, CPAC/registration/registration.py, CPAC/seg_preproc/__init__.py, CPAC/seg_preproc/seg_preproc.py, CPAC/seg_preproc/utils.py, CPAC/utils/configuration.py, dev/docker_data/default_pipeline.yml
Related to #1366 by @sgiavasis
* ♻️ Updates calls to `c.`{configuration keys} in `seg_preproc` to nested versions in [default_pipeline.yml@`45796e`](https://github.com/FCP-INDI/C-PAC/blob/45796e02a091e98da9d65f882b02ea8aa8a10986/dev/docker_data/default_pipeline.yml)
* :rotating_light: Lints those same lines
* :goal_net: Update schema for the above changes
* Includes https://github.com/FCP-INDI/C-PAC/blob/ca14f99040dd8b1a44f913e903df11cc92327961/CPAC/seg_preproc/seg_preproc.py#L1075 and https://github.com/FCP-INDI/C-PAC/blob/ca14f99040dd8b1a44f913e903df11cc92327961/CPAC/anat_preproc/utils.py#L287 from #1405; will need to update https://github.com/FCP-INDI/C-PAC/blob/15fc86d34789ee1b57390ab9858249c0df936eb3/CPAC/seg_preproc/seg_preproc.py#L1211-L1214 once that PR and this one are both …
=> ♻️ Pipeline Builder code changes for nested pipeline config (segmentation)

CPAC/anat_preproc/anat_preproc.py, CPAC/anat_preproc/utils.py, CPAC/func_preproc/func_ingress.py, CPAC/func_preproc/func_preproc.py, CPAC/longitudinal_pipeline/longitudinal_workflow.py, CPAC/pipeline/cpac_basc_pipeline.py, CPAC/pipeline/cpac_cwas_pipeline.py, CPAC/pipeline/cpac_group_runner.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/cpac_randomise_pipeline.py, CPAC/pipeline/cpac_runner.py, CPAC/pipeline/schema.py, CPAC/registration/output_func_to_standard.py, CPAC/utils/utils.py, dev/docker_data/default_pipeline.yml, dev/docker_data/run.py
This PR includes nested config 
1. cpac_pipeline.py line0-711
2. anat_preproc (all) 
index.md`).
<details>
```
Version 1.1
Suite D4700
of my knowledge, is …
```
=> ♻️ Pipeline Builder code changes for nested pipeline config(anat_preproc)

CPAC/nuisance/nuisance.py, CPAC/nuisance/utils/crc.py
Fixes https://github.com/FCP-INDI/C-PAC/issues/1419 by @zeosmar
Fixed the issue when a custom nuisance regressor file is provided
1. Use 0-indexing to fetch dictionary in the list
2. Update encode function to make py3 API happy
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
=> fixed custom regressor file error

CPAC/pipeline/schema.py, CPAC/resources/configs/1.7-1.8-deprecations.yml, CPAC/resources/configs/1.7-1.8-nesting-mappings.yml, CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml, CPAC/resources/configs/pipeline_config_fmriprep-options.yml, CPAC/resources/configs/pipeline_config_monkey.yml, CPAC/resources/configs/pipeline_config_ndmg.yml, CPAC/resources/configs/pipeline_config_nhp-macaque.yml, CPAC/resources/configs/pipeline_config_preproc.yml, CPAC/resources/configs/pipeline_config_regtest-1.yml, CPAC/resources/configs/pipeline_config_regtest-2.yml, CPAC/resources/configs/pipeline_config_regtest-3.yml, CPAC/resources/configs/pipeline_config_regtest-4.yml, CPAC/resources/configs/pipeline_config_rodent.yml, CPAC/resources/configs/test_configs/pipe-test_ABCD.yml, CPAC/resources/configs/test_configs/pipe-test_ANTs-3dSk-AllNuis.yml, CPAC/resources/configs/test_configs/pipe-test_ANTs-3dSk-DistCorr3dSk.yml, CPAC/resources/configs/test_configs/pipe-test_ANTs-3dSk-DistCorrBET.yml, CPAC/resources/configs/test_configs/pipe-test_ANTs-BET-AllNuis.yml, CPAC/resources/configs/test_configs/pipe-test_FNIRT-3dSk-AllNuis.yml, CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-BASC.yml, CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-ISC-voxel.yml, CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-ISC.yml, CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis-MDMR.yml, CPAC/resources/configs/test_configs/pipe-test_FNIRT-BET-AllNuis.yml, CPAC/resources/configs/test_configs/pipe-test_all.yml, CPAC/utils/yaml_template.py, dev/docker_data/default_pipeline.yml
I noticed the `*roi_path` keys were being set to `None` instead of to their respective values when upgrading a pipeline from 1.7 to 1.8.
This PR resolves that issue and updates the preconfigs and test configs accordingly.
Two underlying problems led to this behavior:
1. The YAML writer function skipped values that were dictionaries, assuming they'd be included in the next (deeper) iteration: https://github.com/FCP-INDI/C-PAC/blob/48c83b437bfc488e376fba42ad6b192b8068001d/CPAC/utils/yaml_template.py#L270-L271 This PR updates to add keys not in the template in the appropriate place: https://github.com/FCP-INDI/C-PAC/blob/7c7c663b1fef6df1a4a83f96b6516b597974839a/CPAC/utils/yaml_template.py#L274-L287
2. The regex to find keys in the YAML template didn't match keys that include a URI scheme …
=> 🐛 Include path keys not in template when importing

CPAC/utils/utils.py, dev/docker_data/run.py
… as opposed to entire top-level keys
Fixes 
> Meanwhile, I had a thought:
>   `--pipeline_override`
> 
> As it is, you can give it something like
> ```BASH
>    --pipeline_override "pipeline_setup: {pipeline_name: new-name}"
> ```
> and it will update the nested key, but it overrides the whole `pipeline_setup` in this example. I'm sure that's not what we want.
@shnizzedy 
Updates `--pipeline_override` to be a secret option that will update just the nested keys.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> 🚸 Update `--pipeline_override` to only override keys specified

.circleci/config.yml, conftest.py, dev/circleci_data/test_install.py, variant-ABCD-HCP.Dockerfile
Adds [variant-ABCD-HCP.Dockerfile](https://github.com/FCP-INDI/C-PAC/blob/fd927339a8cd9025f3fc3a02a064d68af10a838b/variant-ABCD-HCP.Dockerfile) to closely match software versions to [DCAN-LABs/abcd-hcp-pipeline:Dockerfile](https://github.com/DCAN-Labs/abcd-hcp-pipeline/blob/e480a8f99534f1b05f37bf44c64827384b69b383/Dockerfile).
| software | C-PAC Dockerfile | abcd-hcp-pipeline Dockerfile | C-PAC-ABCD-HCP variant Dockerfile |
|---|---|---|---|
| **ANTs** | 2.3.4 | 2.2.0 | 2.2.0 |
| **Connectome Workbench** | 1.4.2 | 1.3.2 | 1.3.2 |
| **FSL** | 5.0.9 | 5.0.10 | 5.0.10 |
| **FreeSurfer** | 6.0.0-2beb96c | 1.379.2.73 (5.3-HCP) | 6.0.0-2beb96c |
[variant-ABCD-HCP.Dockerfile](https://github.com/FCP-INDI/C-PAC/blob/fd927339a8cd9025f3fc3a02a064d68af10a838b/variant-ABCD-HCP.Dockerfile) is just …
=> 📌 Create variant Dockerfile for (mostly) matching ABCD-HCP software versions

CPAC/nuisance/nuisance.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/resources/configs/pipeline_config_regtest-1.yml, CPAC/resources/configs/pipeline_config_regtest-2.yml, CPAC/resources/configs/pipeline_config_regtest-3.yml, CPAC/resources/configs/pipeline_config_regtest-4.yml, CPAC/utils/datasource.py
Related to https://github.com/FCP-INDI/cpac_run_logs/issues/15 by @shnizzedy
* Changes `ValueError: Files with same name not allowed` to `UserWarning: File with same name already exists in resource pool. Using existing file`
* Changes `label` to `smlabel` in `else` condition in https://github.com/FCP-INDI/C-PAC/blob/6b263d26203f1ac589d0ce1fe91e970d2c448fff/CPAC/pipeline/engine.py#L623-L630 ↓ https://github.com/FCP-INDI/C-PAC/blob/3384adec4355d7b958c25d23da0805663b59cc71/CPAC/pipeline/engine.py#L624-L631
* Initializes https://github.com/FCP-INDI/C-PAC/blob/3384adec4355d7b958c25d23da0805663b59cc71/CPAC/pipeline/engine.py#L601
* Changes `Exception: [!] No atlas ID found for` to `UserWarning: [!] No atlas ID found for`
index.md`).
visible errors. ― running now. Since the issues are in the …
=> 🐛 `Files with same name not allowed`

CPAC/pipeline/cpac_pipeline.py, CPAC/registration/registration.py, CPAC/vmhc/vmhc.py
Fixes 308ebf8bda3492bbc13d3594a49c8d6b84f6b25b by @sgiavasis 
* Moves the memory estimate from the error-causing place to the appropriate `Node`s and `MapNode`s.
* Adds a `mem_gb` parameter to `apply_transform` to prevent these crashes in future and to <span title="don't repeat yourself">DRY</span> the application of estimates to transforms.
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```
=> ⚡️ Increase memory estimate for apply transform by 0.5 GB

.circleci/config.yml, Dockerfile, variant-lite.Dockerfile, variant-lite.Singularity
Fixes #1280 by @sgiavasis 
Assuming [the test build for the lite variant](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/1502/workflows/6398ff16-1d4b-47bb-997a-3f0eca690937/jobs/5761) succeeds, this PR adds a Dockerfile and a Singularity recipe to build as a variant the same image as the full C-PAC but without FreeSurfer (for a smaller image).
I haven't done any configuration for Docker Hub or Singularity Hub, and won't until next week.
Added CI job to build variant images
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> 📦 Add -lite variant

.circleci/config.yml, CPAC/conftest.py, Singularity.latest-ABCD-HCP, variant-ABCD-HCP.Dockerfile
Updates [`variant/ABCD`](https://github.com/FCP-INDI/C-PAC/tree/fd927339a8cd9025f3fc3a02a064d68af10a838b) to avoid merge conflicts.
Adds [variant-ABCD-HCP.Dockerfile](https://github.com/shnizzedy/C-PAC/blob/4aaaba5464b0e6105bce8e23cfcaca458506816b/variant-ABCD-HCP.Dockerfile) to closely match software versions to [DCAN-LABs/abcd-hcp-pipeline:Dockerfile](https://github.com/DCAN-Labs/abcd-hcp-pipeline/blob/e480a8f99534f1b05f37bf44c64827384b69b383/Dockerfile).
| software | C-PAC Dockerfile | abcd-hcp-pipeline Dockerfile | C-PAC-ABCD-HCP variant Dockerfile |
|---|---|---|---|
| **ANTs** | 2.3.4 | 2.2.0 | 2.2.0 |
| **Connectome Workbench** | 1.4.2 | 1.3.2 | 1.3.2 |
| **FSL** | 5.0.9 | 5.0.10 | 5.0.10 |
| **FreeSurfer** | 6.0.0-2beb96c | 1.379.2.73 (5.3-HCP) | 6.0.0-2beb96c | …
=> 📦 Create variant with software to closely match ABCD-HCP

CPAC/func_preproc/func_preproc.py, CPAC/pipeline/schema.py, CPAC/registration/registration.py, CPAC/resources/configs/pipeline_config_regtest-3.yml, CPAC/utils/tests/data/default_pipeline.yml, dev/docker_data/default_pipeline.yml
Fixes https://github.com/FCP-INDI/C-PAC/issues/1477 by @SucyLi 
1 Change all `selected volume` to `selected_volume`. Somehow `selected volume` doesn't work.
2 Update config field in the node `func_get_selected_RPI`.
index.md`).
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open …
```
=> fix bug: motion correction reference selected volume

CPAC/generate_motion_statistics/test/test_dvars.py
Fixes [test_dvars - generate_motion_statistics.test.test_dvars](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/1589/workflows/23e1617d-0061-4334-9f6a-1a0db032f0a4/jobs/6257/tests#failed-test-0)
- import nibabel
- all(numpy ^_is_close(…))
index.md`).
<details>
```
Version 1.1
Suite D4700
have the …
```
=> ✅ Fix DVARS test

CPAC/func_preproc/func_preproc.py, CPAC/pipeline/schema.py, CPAC/registration/registration.py, CPAC/resources/configs/pipeline_config_fmriprep-options.yml, dev/docker_data/default_pipeline.yml
Related https://github.com/FCP-INDI/C-PAC/issues/1466 by @SucyLi 
Add an option to choose functional brain as BBR reference in fmriprep-options pipeline
index.md`).
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> fmriprep BBR reference

Dockerfile
The issue patched in C-PAC in #1454 by pinning AFNI to v20.0.04 (pre-issue) was resolved in [AFNI 21.0.14](https://github.com/afni/afni/releases/tag/AFNI_21.0.14) (https://github.com/afni/afni/commit/434ef1312350c47db8c8506f37a4b90584cb4672), so we can resume updating AFNI in develop (although we should pin the version at each release).
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```
=> 📌 Unpin AFNI (set to @update.afni.binaries)

CPAC/pipeline/schema.py, CPAC/utils/utils.py
Fixes #1497 by @tbweng
Uses features of all [three proposed designs](https://github.com/FCP-INDI/C-PAC/issues/1497#issuecomment-828551918):
* If any ROIs are specified, ROIs must be fully specified
* The full `*_roi_paths` dictionary can be set empty to clear them all out
* A config can include an optional `roi_paths_fully_specified: False` key/value as a sibling to an `*_roi_paths` to override the default behavior and just update the imported `roi_paths`
[`update_nested_dict`](https://github.com/FCP-INDI/C-PAC/blob/31b0c6c0646d16efc17095b632b373ea181d2438/CPAC/utils/utils.py#L2133) watches for keys that end with `_roi_paths` and short-circuits the update behavior based on the given or implied `roi_paths_full_specified` sibling: https://github.com/FCP-INDI/C-PAC/blob/31b0c6c0646d16efc17095 …
=> 🐛 Allow specifying any ROI paths, including or excluding defaults

CPAC/alff/alff.py, CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/utils/monitoring/monitoring.py
* Decreases `UNDEFINED_SIZE` from `100000000` to `89000000`
* Removes erroneosly large memory estimate for ALFF `bandpass_filtering`
<details>
```
Version 1.1
Suite D4700
of …
```
=> 🚸 Adjust default unknown memory estimates to fit default memory limit

.github/Dockerfiles/neuroparc_Human.Dockerfile, Dockerfile, variant-ABCD-HCP.Dockerfile, variant-fMRIPrep-LTS.Dockerfile, variant-lite.Dockerfile
```BASH
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/neurodata/neuroparc.git/info/lfs'
The command '/bin/sh -c mkdir -p /ndmg_atlases/label &&     GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/neurodata/neuroparc.git /tmp/neuroparc &&     cd /tmp/neuroparc &&     git lfs install --skip-smudge &&     git lfs pull -I "atlases/label/Human/*" &&     cp -r /tmp/neuroparc/atlases/label/Human /ndmg_atlases/label &&     cd -' returned a non-zero code: 2
```
Converts the `# Get atlases` from …
=> 📦️ Use multi-stage for Neuroparc atlases

CPAC/anat_preproc/anat_preproc.py, CPAC/unet/function.py
Fixes #1528 by @XinhuiLi 
- Update U-Net code and model reported in Wang et al., 2021
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
```
=> Upgrade U-Net code and model

dev/docker_data/run.py
Fixes #1476 by @shnizzedy
1. Sets _`--mem_gb` > `--mem_mb` > `maximum_memory_per_participant` in pipeline config > `6.0`_ as preference order for `maximum_memory_per_participant` (before this change the preference order was just _`--mem_gb` > `--mem_mb` > `6.0`_)
2. Specifies in the help strings for those flags and `--n_cpus` that those values are per-participant and which pipeline config values they override.
With the importing-from-default if any values are unspecified, the fallbacks might be unnecessary, but this PR updates the use of the keys with `try` / `except` to check for `KeyError`s and only applying the fallbacks then.
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and …
```
=> 🩹 Use `maximum_memory_per_participant` if included in config

.circleci/config.yml
Updates the CircleCI configuration to use @ChildMindInstituteCNL for its commits.
[![screenshot of commit history from 31e49cb](https://user-images.githubusercontent.com/5974438/130257699-dad63884-604f-4db4-9861-1b05468d75a7.png)](https://github.com/FCP-INDI/C-PAC/commits/31e49cbc4954f1e85749dc1f7fbf0a49a91f62d7)
<details>
```
Version 1.1
Suite D4700
(a) The contribution was created in …
```
=> 👷 Use GitHub machine user for CI commits

CPAC/network_centrality/network_centrality.py, CPAC/network_centrality/pipeline.py, CPAC/network_centrality/utils.py, CPAC/pipeline/engine.py, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml
Fixes #1399 by @shnizzedy 
Fixes an issue where users couldn't set the weight options for network centrality.
Run all weighting options for network centrality and ensure you get all of the outputs.
<details>
```
Version 1.1
Suite D4700
(b) …
```
=> Network Centrality weight options

Dockerfile, variant-fMRIPrep-LTS.Dockerfile, variant-lite.Dockerfile
Fixes #1557 by @shnizzedy & @tergeorge 
Installs the templates expected by [pipeline_config_abcd-options.yml](https://github.com/FCP-INDI/C-PAC/blob/b7de1e46ad5d1d7d34e30e296cb8b18d98a57438/CPAC/resources/configs/pipeline_config_abcd-options.yml)
(https://github.com/FCP-INDI/C-PAC/blob/b7de1e46ad5d1d7d34e30e296cb8b18d98a57438/CPAC/resources/configs/pipeline_config_abcd-options.yml#L85
https://github.com/FCP-INDI/C-PAC/blob/b7de1e46ad5d1d7d34e30e296cb8b18d98a57438/CPAC/resources/configs/pipeline_config_abcd-options.yml#L103
https://github.com/FCP-INDI/C-PAC/blob/b7de1e46ad5d1d7d34e30e296cb8b18d98a57438/CPAC/resources/configs/pipeline_config_abcd-options.yml#L107
https://github.com/FCP-INDI/C-PAC/blob/b7de1e46ad5d1d7d34e30e296cb8b18d98a57438/CPAC/resources/configs/pipeline_config_abcd-option …
=> 📦️ Install DCAN-HCP templates in non-ABCD-HCP-variant images

Dockerfile, variant-ABCD-HCP.Dockerfile, variant-fMRIPrep-LTS.Dockerfile, variant-lite.Dockerfile
Fixes
```python
AttributeError: get_data_files_without_manifest
```
Keeps `setuputils` version under 58.5
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered …
```
=> ⬇️ Keep setuptools < 58.5

CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/pipeline/test/test_nipype_pipeline_engine.py, dev/docker_data/bids_utils.py
Fixes #1591 by @sgiavasis 
The pull request is used to make more flexible BIDS directory parsing (solves issue #1591). When a site directory has a 
sub-directory within it that isn't a sub-{etc} participant directory (like /derivatives), C-PAC will dive into it and call an error message. What this PR does is that it ignores all the sub-directories within the site directory whose name does not start with sub-{etc}. Thus it also takes in the .nii.gz images from the sub-{etc} sub-directory within the site directory for processing.
The main changes regards to this PR was made in the bids_utils.py (lines 379 to 393).
To test: Run C-PAC using a site directory that has sub-directories that has a different name other then sub-{etc}. The script should be able to ignore the other sub-directories …
=> Bids directory parsing  

CHANGELOG.md, CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_monkey-ABCD.yml, CPAC/resources/configs/pipeline_config_monkey.yml, CPAC/resources/configs/pipeline_config_nhp-macaque.yml, dev/docker_data/default_pipeline.yml
Related to https://github.com/FCP-INDI/C-PAC_templates/pull/9 by @shnizzedy 
Use `MacaqueYerkes19` and `J_Macaque_11mo_atlas_nACQ` templates from https://github.com/DCAN-Labs/dcan-macaque-pipeline/tree/master/global/templates as packaged in C-PAC_templates
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
=> 📦️ Get `MacaqueYerkes19` & `J_Macaque_11mo_atlas_nACQ` from DCAN repo

CHANGELOG.md, CPAC/resources/configs/pipeline_config_rodent.yml
In rodent config, updates path to `chd8_functional_template_noise_mask_ag.nii.gz` which has been added to [FCP-INDI/C-PAC_templates](https://github.com/FCP-INDI/C-PAC_templates)
<details>
```
Version 1.1
Suite D4700
(b) The contribution is …
```
=> 📦️ Add CHD8 mouse functional noise mask ag template

.circleci/main.yml
Related to #1553 by @shnizzedy 
Last week the jobs on CircleCI started timing out. This PR serves as a stopgap to run a subset of test environments until #1553 is complete (to build the images on GitHub via multi-stage builds before testing on Circle).
* Skip building (and testing) Singularity images (i.e., build and test only Docker)
* Skip building (and testing) ABCD-HCP & fMRIPrep-LTS varaint images (i.e., build and test only main and lite variant Docker images)
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> 💚 Trim CircleCI workflow

CHANGELOG.md, CPAC/info.py, CPAC/pipeline/nipype_pipeline_engine/__init__.py, CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/utils/monitoring/__init__.py, README.md
Fixes
> Hi, just a minor "Bug" report, on this page: https://github.com/FCP-INDI/C-PAC/blob/main/README.md, the CPAC webiste: The C-PAC website is located here: http://fcp-indi.github.com/, can not be found
― [![Slack](https://cdn.bfldr.com/5H442O3W/at/pl546j-7le8zk-6gwiyo/Slack_Mark.svg?auto=webp&format=png&height=12&width=12) CMI-CNL#user-support](https://cmi-cnl.slack.com/archives/CBM95TMEW/p1638898386001000)
by [![Slack](https://cdn.bfldr.com/5H442O3W/at/pl546j-7le8zk-6gwiyo/Slack_Mark.svg?auto=webp&format=png&height=12&width=12) Lei Cao](https://cmi-cnl.slack.com/team/U02A45L5ZE0)
* Updates all `fcp-indi.github.com` links to `fcp-indi.github.io`
* Removes deprecated OpenNeuro badge from README
* Adds DOI badge for ["Moving Beyond Processing and Analysis-Related Variation in …
=> 📝 Update fcp-indi.gihub.com links to fcp-indi.github.io

CHANGELOG.md, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/utils/monitoring/__init__.py, CPAC/utils/monitoring/custom_logging.py
(Mostly) included in #1616 by @shnizzedy 
For developer debugging, creates a log like [engine.log](https://github.com/FCP-INDI/C-PAC/files/7865460/engine.log) if `pipeline_setup.Debugging.verbose` is `On` in the pipeline config
<details>
```
Version 1.1
Suite D4700 …
```
=> 🔊 Add 'engine.log' for verbose debugging

CHANGELOG.md, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/pipeline/test/test_engine.py
Fixes #1575 by @XinhuiLi & @huguozhen
C-PAC checks if functional data exists before trying to ingress functional data, allowing for anatomical only configurations to run without any functional data.
If a pipeline configuration requires functional data but none are present, an error like
```Python
FileNotFoundError: The provided pipeline configuration requires functional data but no functional data were found for HNU_1/sub-0025427/ses-1. Please check your data and pipeline configurations.
```
is still thrown.
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
=> 🐛 Allow anatomical-data only runs

CPAC/pipeline/cpac_pipeline.py
Fixes #1655 & #1616 by @shnizzedy
Instead of automatically adding all of `[qc_xcp_skullstripped, qc_xcp_native, qc_xcp_template]` when `cfg.pipeline_setup['output_directory']['quality_control']['generate_xcpqc_files']` is on,
* checks for all of `['censor-indices', 'coordinate-transformation', 'dvars', 'framewise-displacement-jenkinson', 'max-displacement', 'movement-parameters', 'rels-displacement']` before adding `qc_xcp_native`,
and 
* checks for `space-template_desc-preproc_bold` before adding `qc_xcp_template`
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> ♻️ Add some conditions for different XCP QC blocks

CHANGELOG.md, CPAC/registration/utils.py, CPAC/resources/cpac_outputs.tsv
Fixes #1616 by @shnizzedy
Fixes #1639 by @tergeorge 
Fixes #1658 by @shnizzedy
Re-resolves merge conflicts from 8f145ba6858a8ce3ac5b3a48a6320693dfb2d1a9
That merge wiped out [the changes to `cpac_outputs.tsv`](https://github.com/FCP-INDI/C-PAC/pull/1616/files#diff-e1c8f266fdc8a7a1b635c8807fb98daa856518b7e16fd15905c31a5e5184b3e8) from #1616, causing connectivity matrices to be misnamed and `*_quality.tsv`s to be missing from the output directory in v1.8.3
Adds https://github.com/FCP-INDI/C-PAC/blob/b9b8acaf3a69f54c53df977b9fb50b2905326504/CPAC/resources/cpac_outputs.tsv#L32-L35 https://github.com/FCP-INDI/C-PAC/blob/b9b8acaf3a69f54c53df977b9fb50b2905326504/CPAC/resources/cpac_outputs.tsv#L126-L127 https://github.com/FCP-INDI/C-PAC/blob/b9b8acaf3a69f54c53df977b9fb50b2905326504/CPAC/resources …
=> 🔀 Fix 8f145ba

CHANGELOG.md, CPAC/pipeline/engine.py, CPAC/pipeline/nipype_pipeline_engine/__init__.py, CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/pipeline/test/test_nipype_pipeline_engine.py, requirements.txt
Related to https://github.com/FCP-INDI/C-PAC/issues/1505 by @shnizzedy
* Adds memory estimation debugging statements to `engine.log`
* Replace `sum` with `max` for initial estimate
<details>
```
Version 1.1
Suite D4700
(b) The contribution …
```
=> ⚡️ Make better initial memory estimation

CPAC/pipeline/check_outputs.py, CPAC/pipeline/engine.py
Fixes #1709 by @shnizzedy
When generating the expected outputs, adds wildcards before each `-` after the first in each BIDS entity and before each `_` between BIDS entities 
I'm not sure multiple `-`s in an entity are BIDS compliant, but we have them and need to handle them here.
* Updated the existing tests to include expected wildcards
* Added https://github.com/FCP-INDI/C-PAC/blob/d467724b22f701f79efaa15ad73fd0f9da4812b5/CPAC/pipeline/check_outputs.py#L99 to the test inputs and updated the outputs accordingly
- I updated the changelog ― n/a, fixing an unreleased feature
- I added or updated documentation  ― n/a, fixing an unreleased feature
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> 🐛 Handle extended BIDS entity values when checked expected outputs

CHANGELOG.md, CPAC/func_preproc/func_preproc.py, CPAC/nuisance/nuisance.py, CPAC/pipeline/engine.py, CPAC/pipeline/schema.py, CPAC/registration/registration.py, dev/docker_data/default_pipeline.yml
Fixes #1741 by @sgiavasis
- Adds a new single-step resampling block which pulls in `desc-preproc_bold` instead of just `desc-stc_bold`.
- Repairs a z-score-standardized derivative write-out issue.
- For preconfigs that use single-step resampling:
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the …
```
=> Single-step resampling with desc-preproc_bold

CHANGELOG.md, CPAC/distortion_correction/distortion_correction.py, CPAC/registration/registration.py
Fixes #1686 by @shnizzedy 
Updates the phase-difference field map resource pool [key naming, including associated outputs](https://github.com/FCP-INDI/C-PAC/blob/80424468c7f4e59c102f446b05d4154ec1cd4b2d/CPAC/distortion_correction/distortion_correction.py#L107-L110).
<details>
```
Version 1.1
Suite D4700
have the right to …
```
=> Fix diffphase_dwell crash

CPAC/resources/configs/pipeline_config_monkey.yml
Updates the `monkey` preconfig to use the same segmentation templates, but versions that are stored locally in the container, instead of pulling from S3.
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based upon previous work …
```
=> Updated the monkey preconfig to use local segmentation atlases

CHANGELOG.md, CPAC/resources/configs/pipeline_config_rbc-options.yml
Removes XCP[e/d]+RBC preprocessing customizations, but keeps distortion correction, nuisance regression and TSE customizations.
<details>
```
Version 1.1
Suite D4700
of my …
```
=> 🔧 Base `rbc-options` on `fmriprep-options`' preproc

dev/docker_data/default_pipeline.yml
Related to https://github.com/FCP-INDI/C-PAC/pull/1761 by @shnizzedy 
Puts a placeholder data config (which imports [the default data config](https://github.com/FCP-INDI/C-PAC/blob/c2ba9d6e40d640f2ca62da1ac039fa80329aae94/CPAC/resources/configs/pipeline_config_default.yml)) in the previous location ([`dev/docker_data/default_pipeline.yml`](https://github.com/FCP-INDI/C-PAC/blob/c2ba9d6e40d640f2ca62da1ac039fa80329aae94/dev/docker_data/default_pipeline.yml)) of the default data config for backwards compatibility, including a comment https://github.com/FCP-INDI/C-PAC/blob/c2ba9d6e40d640f2ca62da1ac039fa80329aae94/dev/docker_data/default_pipeline.yml#L10-L11 about the file move.
<details>
```
Version 1.1 …
```
=> ⚰️ Add placeholder default_pipeline.yml for backwards compatibility

CHANGELOG.md, CPAC/pipeline/random_state/seed.py
Fixes #1795  by @clane9
Fixes how `set_up_random_state` handles number-like `str` and `int` seed arguments.
Check that `cpac run` with `--random_seed 42` and `--random_seed random` run without error.
<details>
```
Version 1.1
Suite D4700
(b) …
```
=> :bug: fix type handling in `set_up_random_state`

.pylintrc, CPAC/pipeline/__init__.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/cpac_runner.py, CPAC/pipeline/random_state/seed.py, CPAC/utils/__init__.py, CPAC/utils/configuration.py, CPAC/utils/configuration/__init__.py, CPAC/utils/configuration/configuration.py, dev/docker_data/run.py
Related to #1774, #1775, #1776 & #1777 by @shnizzedy 
After updating the output directory structure so that `log`, `output` and `working` have matching subdirectories (#1775) and adding a data-config hash to C-PAC generated config filenames (#1777), move those generated config files from the top of the output tree into the `log/sub-${sub}_ses-${ses}`
https://github.com/FCP-INDI/C-PAC/blob/f3aefca12e4d1c47d9a6251e52d05460a4fc4db9/dev/docker_data/run.py#L741-L743
https://github.com/FCP-INDI/C-PAC/blob/f3aefca12e4d1c47d9a6251e52d05460a4fc4db9/CPAC/utils/configuration.py#L481-L494 https://github.com/FCP-INDI/C-PAC/blob/d50f8daa167c4f1834617d6cc70fb436d78f5e5d/CPAC/utils/configuration/configuration.py#L374-L386
<details>
```
Developer …
```
=> 🚚 Move C-PAC generated configs into `log/sub-${sub}_ses-${ses}` subdirectory

.github/Dockerfiles/Ubuntu.bionic-non-free.Dockerfile, .github/Dockerfiles/Ubuntu.xenial-20200114.Dockerfile, .github/scripts/get_package_id.py, .github/workflows/build_stages.yml, CPAC/info.py, requirements.txt
Fixes `ModuleNotFoundError: No module named 'conda.cli.main_info'` by **[:octocat: Actions: Build stages](https://github.com/FCP-INDI/C-PAC/actions/runs/3291230477/jobs/5425119464#step:9:5405)**
* Updates miniconda source in Dockerfiles to a still-published / available version.
* <span name="skiplevel">Pins a skiplevel dependency (`joblib`) to a version (1.0.1) that works with our currently pinned versions of our dependencies that depend on it (`nilearn` and `scikit-learn`)</span>
* Fixes a bug in the workflow that deletes staging images when their branch is deleted
* Updates [deprecated syntax for setting output in :octocat: workflow](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
Restores CI build to success 
<details> …
=> 💚 Fix CI build: Upgrade miniconda (4.8.2 → 4.12.0)

dev/docker_data/run.py
Fixes typo in #1778 by @shnizzedy
Fixes [typo setting the wrong base (`0x444 == 0o2104`) for `chmod`](https://github.com/FCP-INDI/C-PAC/pull/1778#issuecomment-1279402678)
<details>
```
Version 1.1
Suite D4700
(b) The contribution is based …
```
=> ✏️ Fix typo (octal, not hexadecimal)

CHANGELOG.md, CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_rbc-options.yml, CPAC/utils/configuration/yaml_template.py, dev/docker_data/run.py
Fixes 
```Python
extra keys not allowed @ data['disable_log']
```
Removes deprecated `--disable_file_logging` CLI flag that is, before this PR, configurable but does nothing besides assign a boolean to a key in a pipeline configuration.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under the open source …
```
=> 🔥 Remove deprecated `--disable_file_logging` CLI flag

CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml, CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_rbc-options.yml, CPAC/resources/configs/pipeline_config_regtest-1.yml, CPAC/resources/configs/pipeline_config_regtest-2.yml, CPAC/resources/configs/pipeline_config_regtest-3.yml, CPAC/resources/configs/pipeline_config_regtest-4.yml
* Turns f/alff and network centrality on
* Sets weight options to `binarized` for degree centrality, both options for lfcd, and none for eigenvector centrality
* Turns off all weight options for network centrality in blank preconfig and adjusts all other preconfigs accordingly
Leaves the rest of the config defaulting to what's in blank. Is that what we want here?
from
https://github.com/FCP-INDI/C-PAC/blob/d629ef79e7e3279b4b548dcb742e9c1100ea3503/CPAC/resources/configs/pipeline_config_blank.yml#L1362-L1372 https://github.com/FCP-INDI/C-PAC/blob/d629ef79e7e3279b4b548dcb742e9c1100ea3503/CPAC/resources/configs/pipeline_config_blank.yml#L1414-L1480
with these overrides
https://github.com/FCP-INDI/C-PAC/blob/d629ef79e7e3279b4b548dcb742e9c1100ea3503/CPAC/resources/configs/pipeline_config_rbc-opt …
=> 🔧 rbc-options: Turn on f/alff, lfcd, binarized degree centrality

CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/registration/registration.py, CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_rbc-options.yml, CPAC/resources/cpac_outputs.tsv, CPAC/utils/utils.py
Related to #1808 by @shnizzedy 
- Writes out whole-head T1w in native and template space.
- Writes out T1w brain mask in template space.
- Includes session directory level in output directory.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> RBC Output directory upgrades Pt. 1

CPAC/pipeline/check_outputs.py, CPAC/pipeline/engine.py, CPAC/utils/__init__.py
Fixes [![:slack:](https://cdn.brandfolder.io/5H442O3W/at/pl546j-7le8zk-6gwiyo/Slack_Mark.png?width=12&height=12) missing outputs](https://cmi-cnl.slack.com/archives/GC8KKE490/p1667938144677039) by @amygutierrez 
Adds a level of depth for expected outputs check to account for
> * Includes session directory level in output directory.
from https://github.com/FCP-INDI/C-PAC/pull/1820
<details>
```
Version 1.1
Suite D4700
By making a contribution to …
```
=> 🥅 Update expected outputs check to match updated derivatives structure

.github/workflows/build_stages.yml, CPAC/pipeline/cpac_runner.py, dev/docker_data/run.py
Fixes errantly passing smoke tests by @amygutierrez & @gkiar 
Updates [`dev/docker_data/run.py`](https://github.com/FCP-INDI/C-PAC/blob/2bce9637dac042d835c764a0ca0137164d6fb0c1/dev/docker_data/run.py) to exit with exit code 1 if [`CPAC.pipeline.cpac_runner.run`](https://github.com/FCP-INDI/C-PAC/blob/2bce9637dac042d835c764a0ca0137164d6fb0c1/CPAC/pipeline/cpac_runner.py#L218-L669) returns an exit code 1
Also tweaks the CI logic for whether to build a branch-specific testing image
<details>
```
Version 1.1
Suite D4700
license …
```
=> 🥅 Set exit code to 1 if graph build fails

CPAC/resources/cpac_outputs.tsv
Fixes #1805 & #1820 by @sgiavasis
Adds missing empty cells in `cpac_outputs.tsv`
[`develop`](https://github.com/FCP-INDI/C-PAC/blob/3a248ef0e1075eb7a1c5490ebfb561ea1f3c3941/CPAC/resources/cpac_outputs.tsv) | [`fix/outputs_table`](https://github.com/FCP-INDI/C-PAC/blob/84fff57020f60778e65b07aafc2c227f5211400b/CPAC/resources/cpac_outputs.tsv)
--- | ---
<details>
```
Version 1.1
Suite D4700 …
```
=> 🎨 Add missing empty cells in `cpac_outputs.tsv`

CPAC/pipeline/schema.py, CPAC/pipeline/test/test_schema_validation.py
Adds a check to the participant pipeline config validator to ensure single-step resampling isn't trying to use FSL registrations.
https://github.com/FCP-INDI/C-PAC/blob/65e0b652744d6c8baf8c3a65f99ff4ddd09a0562/CPAC/pipeline/test/test_schema_validation.py#L31-L48
<details>
```
Version 1.1
Suite D4700
have the right to submit …
```
=> 🥅 Validation: require ANTS registration for single-step resampling

CHANGELOG.md, CPAC/alff/alff.py, CPAC/distortion_correction/distortion_correction.py, CPAC/nuisance/nuisance.py, CPAC/pipeline/cpac_pipeline.py, CPAC/registration/registration.py, CPAC/resources/configs/pipeline_config_rbc-options.yml
Related to #1072  by @ccraddock, #1242 by @sgiavasis, and #1625 by @sgiavasis 
- Applies the distortion correction unwarps (all kinds) to the BOLD time series even when the type of warp field (ANTs or FSL) does not match which registration tool the pipeline or pipeline variant is based on.
- Further improved the flexibility with reading in and detecting which field maps are present based on different naming conventions.
- Incidentally, fixes a small connection error with ALFF and f/ALFF if frequency filtering is turned off.
- Note: Different FSL tools use different formats for phase-encoding direction input arguments. PE direction conversion function has been updated to handle these different conversions.
<details>
```
Developer …
```
=> Repair distortion correction unwarp applications

CPAC/alff/alff.py, CPAC/func_preproc/func_preproc.py, CPAC/nuisance/nuisance.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/registration/registration.py, CPAC/reho/reho.py
Fixes #1840 by @sgiavasis 
- Creates template-space derivative-resolution time series in resource pool, in addition to the usual functional-resolution.
- Submits the derivative-resolution time series to any template-space processing.
- Also fixes distortion correction warp applications to also apply the warps to `desc-stc_bold` or `bold` in the case of single-step resampling or the ABCD-style BOLD warp-to-template. (Without this, the distortion correction warps would be applied to the preprocessed BOLD in native space, and this version would not proceed to the warp to template).
<details>
```
Version 1.1
Suite D4700
San …
```
=> Derivative-resolution time series processing

CPAC/pipeline/check_outputs.py, CPAC/resources/configs/pipeline_config_abcd-options.yml, CPAC/utils/bids_utils.py
Fixes 
> no crashes, but show Missing Outputs
by @amygutierrez 
Instead of just looking for outputs in `output/sub-{SUB}/ses-{SES}`, look in all of
* `output/sub-{SUB}/ses-{SES}`
* `output/{SUB}/ses-{SES}`
* `output/sub-{SUB}/{SES}`
* `output/{SUB}/{SES}`
I think in a future release we should enforce the output directories being `output/sub-{SUB}/ses-{SES}` but that this PR should resolve this current issue.
:pencil2: Also [fixes a typo (removes an extra `/`)](https://github.com/FCP-INDI/C-PAC/pull/1844/commits/1dd3ca82064c008f16857b86d080ebed11194a3b)
<details>
```
Version 1.1
Suite D4700
Everyone …
```
=> 🐛 Fix expected outputs check to better find outputs

CPAC/resources/cpac_outputs.tsv
Fixes [exclude `desc-reorient_T1w`](https://docs.google.com/spreadsheets/d/1YVTKy7TlnCBJ6AXqzimbzkMo1Cnf7WqFiySj3T5ih8U#gid=0&range=A4:B4) by RBC working group /
> do we want to write out desc-reorient?
by @sgiavasis 
<details>
```
Version 1.1
Suite D4700
indicated …
```
=> 🔧 Make `desc-reorient_T1w` a debugging output

CHANGELOG.md, CPAC/pipeline/engine.py
Fixes 
> `freesurfer-subject-dir` doesn't seem to populate anymore when you provide one in the pipe config- I suspect that got clobbered when we moved to the templates CSV: https://github.com/FCP-INDI/C-PAC/blob/9586d7146eff224200e18622523a56da6a9826a6/CPAC/pipeline/engine.py#L1731
[by](https://cmi-cnl.slack.com/archives/GC8KKE490/p1668638020187769) @sgiavasis 
Reverts a code block deletion from f956f39ac343ce2b4cc28e8c752582bd21e4b9e3:
parent to revert to | change to revert | this PR
---|---|---
https://github.com/FCP-INDI/C-PAC/blob/72d56cb34966a9f1624a078f44323812955f4f1d/CPAC/pipeline/engine.py#L1736-L1752 | https://github.com/FCP-INDI/C-PAC/blob/f956f39ac343ce2b4cc28e8c752582bd21e4b9e3/CPAC/pipeline/engine.py#L1724-L1727 | https://github.com/FCP-INDI/C-PAC/blob/14fa5e37777a5bbda191386 …
=> 🐛 Restore `freesurfer_dir` ingress from pipeline config

.github/workflows/check_updated_preconfigs.yml
Fixes #1756 by @shnizzedy 
Updates the version-update-check script to update the version-specific stage image tags in other stage images' recipes.
Set https://github.com/FCP-INDI/C-PAC/blob/f622a7825795451c466027233c2d1337c2251a09/CPAC/info.py#L47 and the let the CI [do its thing](https://github.com/FCP-INDI/C-PAC/actions/runs/3605412054/jobs/6075784089)
[![https://github.com/FCP-INDI/C-PAC/commit/f622a7825795451c466027233c2d1337c2251a09](https://user-images.githubusercontent.com/5974438/205399485-a653218b-1cc5-4273-a89b-445451e961fa.png)](https://github.com/FCP-INDI/C-PAC/commit/f622a7825795451c466027233c2d1337c2251a09)
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
=> 👷 Update stage tags on version change

.github/workflows/build_C-PAC.yml, .github/workflows/check_updated_preconfigs.yml, .github/workflows/delete_images.yml, .github/workflows/deploy_to_Docker_Hub.yml, CHANGELOG.md, CONTRIBUTING.md, CPAC/info.py, CPAC/pipeline/check_outputs.py, CPAC/pipeline/engine.py, CPAC/resources/cpac_outputs.tsv, CPAC/utils/utils.py
Fixes [🔖 `v1.8.5rc0`](https://github.com/FCP-INDI/C-PAC/releases/tag/v1.8.5rc0) by @sgiavasis 
The [`HEAD` of this branch](https://github.com/FCP-INDI/C-PAC/commit/e310fd266351b09492e4676a780562d735d90295) is [🔖 `v1.8.5.dev1`](https://github.com/FCP-INDI/C-PAC/releases/tag/v1.8.5.dev1)
- Changed CI logic to allow non-release tags
- Fixes bug in yellow path in this flowchart 
- Makes `desc-brain` `bold` and `T1w` optional debugging outputs
- Moved `ExpectedOutputs` logic to calculate later in graph building for more precision and replaced any straggling `space-template`s with `space-*`s
- Branches from `develop` at baea467a4f7ffd24b0898c8e4a46a0ec8e9e5f28 (before #1851)
[![https://github.com/FCP-INDI/C-PAC/network](https://user-images.githubusercontent.com/5974438/207431969-c1d25446-8ef7-48 …
=> 🔖 1.8.5 prerelease fixes

.circleci/main.yml, .github/Dockerfiles/FSL.5.0.9-5.neurodebian-xenial.Dockerfile, .github/Dockerfiles/base-standard.Dockerfile, CHANGELOG.md, CPAC/resources/tests/test_permissions.py
Fixes [`ERROR (nifti_image_read): failed to find header file for 'T1w-brain-template-symmetric-deriv/MNI152_T1_3mm_brain_symmetric.nii.gz' invalid input dataset`](https://drive.google.com/drive/folders/1UOvoU_0Ik7x8xMmXmggmEYrUEsz2681q) by @amygutierrez 
For some reason 3 of the standard FSL templates were packaged with no ‘group’ or ‘public’ permissions.
https://github.com/FCP-INDI/C-PAC/blob/c4285023282cb02e235c1f7d3b40e8232398d3f7/CPAC/resources/tests/test_permissions.py#L24-L29
https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/4538/workflows/cbf78a94-fad1-42c3-b934-1fb5a3b1f1f2/jobs/23864?invite=true#step-108-109
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and its …
```
=> 🛂 Make standard FSL templates public read accessible

CPAC/resources/cpac_outputs.tsv
Fixes #1787 by @diegoaper
Converts soft tabs into tabs for MDMR rows in `cpac_outputs.tsv`.
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an …
```
=> 🐛 Fix delimiters in MDMR outputs

CPAC/__main__.py
Remove `__main__.alf()`.
The only thing this did was call `alff.run_alf()` which was does not exist for a while (https://github.com/FCP-INDI/C-PAC/commit/2bc49dccecf6a6821fa899e88026ecb08d9370ed) so it is most likely unused at this point.
If it is not (meant to be) unused let me know, then I will fix/try to recreate the original behavior.
- [x My commit messages follow best practices.
- I found no references to the removed function
<details>
```
Version 1.1
Suite D4700
Developer's …
```
=> Remove broken alff cli from CPAC.__main__

CHANGELOG.md, CPAC/func_preproc/utils.py
Fixes 
```Python
ValueError: w0 should be such that 0 < w0 < 1
```
discovered when testing #1860 by @shnizzedy 
Passes sampling frequency to `scipy.signal.iirnotch(w0, Q, fs=2.0)` instead of relying on the default.
<details>
```
Version 1.1
Suite D4700
indicated in …
```
=> 🐛 Pass sampling frequency to `iirnotch`

CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/pipeline/random_state/seed.py, CPAC/registration/registration.py, CPAC/surface/surf_preproc.py, CPAC/utils/monitoring/custom_logging.py, CPAC/utils/monitoring/draw_gantt_chart.py
* Adds capability to include logs from subprocesses in C-PAC's log files
* Restores broken `engine.log` and `random.log`
I wrote a `log_subprocess` function that logs like [this](https://gist.github.com/shnizzedy/21d9e9388fe71f84b264d96fcffb1f56#file-230112-06-01-05-33-nipype-interface-info-log) when a subprocess command succeeds and like [this](https://gist.github.com/shnizzedy/21d9e9388fe71f84b264d96fcffb1f56#file-230111-19-02-53-749-nipype-interface-error-log) when it fails.
The pipeline will still crash when a subprocess crashes (optionally, with `raise_error=False` to turn it off).
You can replace
```Python
subprocess.check_output
```
with
```Python
log_subprocess
```
(and replace `import subprocess` with `from CPAC.utils.monitoring.custom_logging import log_subprocess`) to get the …
=> 🔊 Update logging

CPAC/connectome/connectivity_matrix.py, CPAC/nuisance/nuisance.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/pipeline/random_state/seed.py, CPAC/registration/registration.py, CPAC/resources/cpac_outputs.tsv, CPAC/resources/templates/BIDS_identifiers.tsv, CPAC/sca/sca.py, CPAC/timeseries/timeseries_analysis.py, CPAC/utils/__init__.py, CPAC/utils/bids_utils.py, CPAC/utils/datasource.py, CPAC/utils/monitoring/custom_logging.py, CPAC/utils/monitoring/draw_gantt_chart.py, CPAC/utils/tests/test_bids_utils.py, CPAC/utils/utils.py, dev/docker_data/run.py
* Fixes some points where node names were being duplicated
* Includes `movement-parameters` in linked inputs for template-space nuisance regression
* Fixes bug where https://github.com/FCP-INDI/C-PAC/blob/ea59c5f79a76c0d537b2cbcdf16c8b15ddc86477/CPAC/func_preproc/func_preproc.py#L1304-L1305 were not getting labeled with `filt-*`<span id="backlink1" name="backlink1"><sup>[[1]](#unspecified-data)</sup></span>
* Inserts an `_` between the node name and subnode index in `MapNode`s
* Caches to disk when using Nilearn to calculate connectome correlation matrices
* Adds BIDS label `MNI152NLin2009cAsym` to `/code/CPAC/resources/templates/mni_icbm152_t1_tal_nlin_asym_09c.nii` (related: https://github.com/FCP-INDI/C-PAC_templates/issues/18)
* Drops `space` and `res` from atlas entities when …
=>  🐛 Fixes for Paul's 24-fork pipeline

.github/README.md
Adds a small README with a flowchart illustrating the relationship between the workflow files in [`.github`](https://github.com/FCP-INDI/C-PAC/tree/46d41981a00682b3835587637c15e15dd3fe5663/.github)
[![https://github.com/FCP-INDI/C-PAC/tree/46d41981a00682b3835587637c15e15dd3fe5663/.github](https://user-images.githubusercontent.com/5974438/219496194-b0ccc713-fb2b-4b19-abb3-5b96288e7e5e.png)](https://github.com/FCP-INDI/C-PAC/tree/46d41981a00682b3835587637c15e15dd3fe5663/.github)
<details>
```
Version 1.1
Suite D4700
license …
```
=> 📝 Document GitHub Actions

CHANGELOG.md, CPAC/anat_preproc/anat_preproc.py, CPAC/anat_preproc/utils.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/pipeline/schema.py, CPAC/registration/registration.py, CPAC/resources/configs/pipeline_config_abcd-options.yml, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml, CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_ccs-options.yml, CPAC/resources/configs/pipeline_config_default.yml, CPAC/resources/configs/pipeline_config_fmriprep-options.yml, CPAC/resources/configs/pipeline_config_monkey.yml, CPAC/resources/configs/pipeline_config_regtest-2.yml, CPAC/resources/configs/pipeline_config_regtest-3.yml, CPAC/seg_preproc/seg_preproc.py, CPAC/surface/surf_preproc.py
1. Separate generation of tissue masks and brain mask in Freesurfer workflow
2. Add FreeSurfer-Brainmask brain extraction option so users can select if they would like to use Freesurfer-generated masks
3. New pipeline switch for Freesurfer ingress to streamline ingress workflow
<details>
```
Version 1.1
Suite D4700
have the …
```
=> ➡️ New FreeSurfer ingress workflow

CPAC/anat_preproc/anat_preproc.py, CPAC/pipeline/cpac_pipeline.py, CPAC/resources/configs/pipeline_config_ccs-options.yml, CPAC/surface/surf_preproc.py
Debugs errors in ccs-options pipeline and adds a check before appending 'reconall' to freesurfer folder path.
<details>
```
Version 1.1
Suite D4700
of my knowledge, is …
```
=> ccs-options bugfix & check for reconall path in freesurfer_folder

CPAC/pipeline/cpac_pipeline.py, CPAC/seg_preproc/seg_preproc.py
Fixed issue with FreeSurfer tissue segmentation option
<details>
```
Version 1.1
Suite D4700
license and I have …
```
=> Fix bugs in FreeSurfer tissue seg option

.github/Dockerfiles/base-ABCD-HCP.Dockerfile
<details>
```
Version 1.1
Suite D4700
license and I have the …
```
=> :package: Rebuild wb_command in ABCD base image

.github/Dockerfiles/Ubuntu.bionic-non-free.Dockerfile, requirements.txt
Fixes [Build C-PAC Ubuntu (Ubuntu.bionic-non-free): Build and push Docker image](https://github.com/FCP-INDI/C-PAC/actions/runs/4472611236/jobs/7858984902#step:9:4125)
```
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c conda update conda -y &&     conda install nomkl &&     conda install -y        blas       cython       matplotlib==3.1.3       networkx==2.4       nose==1.3.7       numpy==1.16.4       pandas==1.0.5       scipy==1.6.3       traits==4.6.0       wxpython       pip &&     pip install       torch==1.2.0 torchvision==0.4.0 -f https://download.pytorch.org/whl/torch_stable.html &&     pip install --upgrade setuptools &&     pip install --upgrade pip &&     pip install -r /opt/requirements.txt &&     pip install xvfbwrapper &&     curl -s …
```
=> 📦️ Fix bionic build

.github/stage_requirements/phase_one.txt, .github/stage_requirements/phase_three.txt, .github/stage_requirements/phase_two.txt, .github/workflows/build_C-PAC.yml, .github/workflows/build_and_test.yml, .github/workflows/build_stages.yml, .github/workflows/delete_images.yml, .github/workflows/on_push.yml, .github/workflows/smoke_test_participant.yml
Just-the-CI-changes from https://github.com/FCP-INDI/C-PAC/pull/1916#actions by @shnizzedy 
Refactors the CI flow from a series of `workflow_dispatch`es to a series of `workflow_call`s
[![https://github.com/FCP-INDI/C-PAC/actions/runs/4547655117](https://user-images.githubusercontent.com/5974438/228367334-3163f463-b62c-4f15-a24f-af5f2a382074.png)](https://github.com/FCP-INDI/C-PAC/actions/runs/4547655117)
<details>
```
Version 1.1
Suite D4700 …
```
=> 👷 `workflow_dispatch` → `workflow_call`

CPAC/anat_preproc/anat_preproc.py, CPAC/pipeline/engine.py, CPAC/seg_preproc/seg_preproc.py
Added a transformation step to bring the wmparc.mgz file to MNI space
<details>
```
Version 1.1
Suite D4700 …
```
=> 🐛 Fix FreeSurfer ingress misalignment

CPAC/anat_preproc/anat_preproc.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/resources/configs/pipeline_config_abcd-options.yml, CPAC/surface/globals.py, CPAC/surface/surf_preproc.py, CPAC/utils/configuration/configuration.py, CPAC/utils/configuration/yaml_template.py
Remove ReconAll doublerun guard, fix registration step in freesurfer-ABCD-brainmask, make default value True for run_reconall in abcd-options preconfig, added a warning if Freesurfer ingress directory paths are invalid, and fixed ACPC workflow forking.
<details>
```
Version 1.1
Suite D4700
have the right to submit it under …
```
=> 🐛 Fix bug in abcd-options workflow

.github/workflows/smoke_test_participant.yml, CPAC/pipeline/__init__.py, CPAC/resources/configs/pipeline_config_abcd-options.yml, CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_benchmark-ANTS.yml, CPAC/resources/configs/pipeline_config_benchmark-FNIRT.yml, CPAC/resources/configs/pipeline_config_default-deprecated.yml, CPAC/resources/configs/pipeline_config_fmriprep-options.yml, CPAC/resources/configs/pipeline_config_fx-options.yml, CPAC/resources/configs/pipeline_config_monkey-ABCD.yml, CPAC/resources/configs/pipeline_config_monkey.yml, CPAC/resources/configs/pipeline_config_ndmg.yml, CPAC/resources/configs/pipeline_config_nhp-macaque.yml, CPAC/resources/configs/pipeline_config_preproc.yml, CPAC/resources/configs/pipeline_config_rbc-options.yml, CPAC/resources/configs/pipeline_config_regtest-1.yml, CPAC/resources/configs/pipeline_config_regtest-2.yml, CPAC/resources/configs/pipeline_config_regtest-3.yml, CPAC/resources/configs/pipeline_config_regtest-4.yml, CPAC/resources/configs/pipeline_config_rodent.yml
Removes `monkey-ABCD` tests from 1.8.5 develop branch and removes `monkey-ABCD` from listed preconfigs.
These tests are failing.
<details>
```
Version 1.1
Suite D4700
of my …
```
=> 🔥 Remove `monkey-ABCD` tests for 1.8.5

CPAC/anat_preproc/anat_preproc.py, CPAC/nuisance/nuisance.py, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py
Merging two fmriprep ingress branches
<details>
```
Version 1.1
Suite D4700
license and I have the right under …
```
=> Fmriprep ingress

CPAC/anat_preproc/anat_preproc.py, CPAC/surface/fMRISurface/SubcorticalProcessing.sh
Revert [commit](https://github.com/FCP-INDI/C-PAC/pull/1932/commits/68438897e93d14a56575298d08cc59037397607a) that made inputs for `acpc_align_head` into a list, since this caused forking.
Also changed permissions for the temp folder created in `SubcorticalProcessing.sh` from 770 to 775 so that subprocess doesn't run into permissions issues.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> :wrench: Fix forking list issue

.github/Dockerfiles/C-PAC.develop-lite-bionic.Dockerfile, CHANGELOG.md, CPAC/anat_preproc/anat_preproc.py, CPAC/unet/__init__.py, CPAC/unet/_torch.py, requirements.txt
Fixes [failing `unet` tests](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/5807/workflows/0ac5bd1d-6866-4512-b7c5-cef1de85d561/jobs/27540/tests)
Related to (currently unmerged) changes from #1971 by @shnizzedy 
Torch is a huge Python package (~2GB) that is rarely used. Instead of including it by default, we now install it at runtime iff we're going to need it https://github.com/FCP-INDI/C-PAC/blob/22880e473df433ea9014512ec770d11967a905b9/CPAC/unet/_torch.py#L17-L27
Torch was removed from staging images in #1971 which has not yet been merged; this PR is just the code to install `torch` as-needed.
This should fix 4 tests that are failing in [current `develop`](https://github.com/FCP-INDI/C-PAC/tree/02344db) and its branches
<details>
<summary>Developer Certificate of …
=> 📦️ Install `torch` iff needed

.github/Dockerfiles/C-PAC.develop-ABCD-HCP-bionic.Dockerfile, .github/Dockerfiles/C-PAC.develop-bionic.Dockerfile, .github/Dockerfiles/C-PAC.develop-fMRIPrep-LTS-xenial.Dockerfile, .github/Dockerfiles/C-PAC.develop-lite-bionic.Dockerfile, .github/Dockerfiles/Ubuntu.bionic-non-free.Dockerfile, .github/Dockerfiles/base-ABCD-HCP.Dockerfile, CPAC/info.py, CPAC/unet/_torch.py
Fixes #1973 by @shnizzedy
Prior to this PR, the functionality of #1973 works for `root` and for the built-in user `c-pac_user` but not for any other arbitrary user. This PR updates in-container permissions and settings in the affected C-PAC images to allow this functionality to work the same regardless of the specified user.
We set very open permissions on `/home/c-pac_user` https://github.com/FCP-INDI/C-PAC/blob/aafa0bc964b3a2a9a0df9b444009bbff60ae4042/.github/Dockerfiles/Ubuntu.bionic-non-free.Dockerfile#L28, set https://github.com/FCP-INDI/C-PAC/blob/aafa0bc964b3a2a9a0df9b444009bbff60ae4042/.github/Dockerfiles/C-PAC.develop-lite-bionic.Dockerfile#L40, and `pip install --user` between two cache clears: https://github.com/FCP-INDI/C-PAC/blob/aafa0bc964b3a2a9a0df9b444009bbff60ae4042/CPAC/u …
=> 🐛 Install torch iff necessary for arbitrary user

.github/Dockerfiles/base-standard.Dockerfile, CPAC/surface/tests/test_installation.py
Fixes
```BASH
bash: /usr/lib/freesurfer/bin/avi2talxfm: /bin/csh: bad interpreter: No such file or directory
```
Hardlinks `$(which tcsh)` → `/bin/csh` so C Shell will be in `$PATH`
`tcsh` is a fully backwards-compatible C Shell fork that's already installed in the image.
https://github.com/FCP-INDI/C-PAC/blob/04e35407c014db5d8ee800000cfc29e09e290eae/CPAC/surface/tests/test_installation.py#L23-L31
<details>
```
Version 1.1
Suite D4700
By making …
```
=> ➕ Install `csh` if we have FreeSurfer

CPAC/func_preproc/func_motion.py, CPAC/func_preproc/func_preproc.py, CPAC/pipeline/nodeblock.py, CPAC/pipeline/utils.py
Documents https://github.com/FCP-INDI/C-PAC/pull/1919#issuecomment-1664694980 by @sgiavasis
Documents #1919 by @shnizzedy
Required for https://github.com/FCP-INDI/fcp-indi.github.io/pull/306 by @shnizzedy 
A couple more commits for the series of docstring updates beginning with https://github.com/FCP-INDI/C-PAC/commit/ab3ba219331df7cb778f8a8425896a2921200ab6
* Mostly just reformatting some docstrings into ReStructuredText
* <span title="single-source-of-truth'ing">SSOTing</span> https://github.com/FCP-INDI/C-PAC/blob/cf8c0204acd87ae01d196969cad82931f263be7a/CPAC/pipeline/nodeblock.py#L61-L82 for NodeBlockFunctions
<details>
```
Version 1.1 …
```
=> 📝 Documentation updates for FCP-INDI/fcp-indi.github.io#306 (📝 Document FCP-INDI/C-PAC#1919 (👔 Use filtered movement parameters to calculate FD-J))

CPAC/utils/datasource.py
Tiny followup to #1990 by @shnizzedy in case this function causes problems for anyone in addition to me and @e-kenneally before https://github.com/shnizzedy/C-PAC/tree/regression/after-runs gets merged in
Applies https://github.com/FCP-INDI/C-PAC/blob/abbacaf55d6eb92062eafece8325d56c59c9d0e3/CPAC/utils/interfaces/function/function.py#L112 to https://github.com/FCP-INDI/C-PAC/blob/89c788773bec4caae8c264ad807e680107e19bb5/CPAC/utils/datasource.py#L372-L374 to handle type-hinting tuples for Python⋛3.10 (https://github.com/FCP-INDI/C-PAC/blob/89c788773bec4caae8c264ad807e680107e19bb5/CPAC/utils/typing.py#L34-L40)
<details>
```
Version 1.1
1 …
```
=> 🐛 Import custom `TUPLE` type for `Function` Node function `calc_delta_te_and_asym_ratio`

.github/Dockerfiles/C-PAC.develop-ABCD-HCP-bionic.Dockerfile, .github/Dockerfiles/C-PAC.develop-fMRIPrep-LTS-xenial.Dockerfile, .github/Dockerfiles/C-PAC.develop-jammy.Dockerfile, .github/Dockerfiles/C-PAC.develop-lite-jammy.Dockerfile
Repeats #1927 by @shnizzedy & @amygutierrez, but to [`develop`]((https://github.com/FCP-INDI/C-PAC/tree/develop)) instead of to [`regression/reg-suite`](https://github.com/FCP-INDI/C-PAC/tree/regression/reg-suite)
In the final Docker build stages, change the default working directory from `/` to `/home/c-pac_user` (which should be anyone read-writeable)
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> 📦️ Restore `WORKDIR` to final-stage Dockerfiles

CPAC/func_preproc/func_preproc.py, CPAC/pipeline/schema.py, CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_default.yml
I added a switch for `func_reorient` within `functional_preproc` so that it can run independently of the functional preproc workflow. With fmriPrep ingress, `functional_preproc` is off, but `func_reorient` is required to run despiking. This switch allows these blocks to run even without `func_preproc`.
Ran despiking locally with fmriprep-ingress config options.
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I …
```
=> :wrench: Add func_reorient switch 

.github/workflows/regression_test_lite.yml
Related to #2001 by @amygutierrez and @shnizzedy 
Reverts 8e6374a ‒ a5a6c8a (which didn't work as intended) and adds a `workflow_dispatch` trigger, so instead of getting 1 ‒ 2 ACCESS runs triggered on PR actions, we'll get 0 ‒ 1 and can manually trigger one (with the API or the web GUI) when we want one that didn't trigger automatically.
<details>
```
Version 1.1
Suite D4700
(a) The …
```
=> 👷 Update ACCESS deployment triggers

CPAC/utils/utils.py
If scan parameters are missing or not found, `template` was uninitialized. We may want to raise an exception if scan parameters are missing or not found, but probably not a `NameError`.
<details>
```
Version 1.1
Suite D4700
(b) The …
```
=> 🐛 Initialize uninitialized variables

.github/Dockerfiles/base-lite.Dockerfile
Fixes
```
--------------------------------------------------------------------------------------
Error locating ANTS
--------------------------------------------------------------------------------------
It seems that the ANTSPATH environment variable is not set. Please add the ANTSPATH
variable. This can be achieved by editing the .bash_profile in the home directory.
```
We need it here: https://github.com/FCP-INDI/C-PAC/blob/72120f4c6a7fa8695fb1817bf832cc23c8a89d12/CPAC/seg_preproc/utils.py#L341
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies of …
```
=> 📦️ Set `ANTSPATH` in lite and standard images

.github/Dockerfiles/base-lite.Dockerfile, CPAC/pipeline/cpac_pipeline.py, CPAC/pipeline/engine.py, CPAC/pipeline/utils.py
Update the release candidate branch for v1.8.6 for last-minute `develop` branch PRs.
=> Update release candidate v1.8.6.

CPAC/anat_preproc/anat_preproc.py, CPAC/resources/configs/pipeline_config_anat-only.yml, CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_default.yml, CPAC/resources/configs/pipeline_config_fmriprep-options.yml
Fixes #2052 by @sgiavasis 
- Hard-coded the -m flag in the FSL BET [block](https://github.com/FCP-INDI/C-PAC/blob/v1.8.6/CPAC/anat_preproc/anat_preproc.py#L618-L620).
- The `mask_boolean` keys in all of the configs are removed.
Run one of the `config` and check to see `working` directory to see if mask image is there inside the `anat_BET_skullstrip` folder
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify …
```
=> Mask boolean default on

.github/Dockerfiles/C-PAC.develop-ABCD-HCP-bionic.Dockerfile, .github/Dockerfiles/C-PAC.develop-fMRIPrep-LTS-xenial.Dockerfile, .github/Dockerfiles/C-PAC.develop-jammy.Dockerfile, .github/Dockerfiles/C-PAC.develop-lite-jammy.Dockerfile, .github/Dockerfiles/base-standard.Dockerfile, .github/scripts/autoversioning.sh, CPAC/__init__.py, CPAC/info.py, CPAC/pipeline/schema.py, Dockerfile, variant-ABCD-HCP.Dockerfile, variant-fMRIPrep-LTS.Dockerfile, variant-lite.Dockerfile
Fixes #2055 and #2046 by @shnizzedy 
* Replaces https://github.com/FCP-INDI/C-PAC/blob/c706bf2b2e9e58af10aa6346e3148447a0bbebf9/.github/scripts/autoversioning.sh#L34 with https://github.com/FCP-INDI/C-PAC/blob/9884409e68b0e2aaa13e9eb903ca8e1d74aeb6ec/.github/scripts/autoversioning.sh#L34 to get previous and current canonical version strings
* Adds previously missing conditional for Mac-vs-Linux `sed` for Dockerfile updates https://github.com/FCP-INDI/C-PAC/blob/9884409e68b0e2aaa13e9eb903ca8e1d74aeb6ec/.github/scripts/autoversioning.sh#L44-L50
* Replaces https://github.com/FCP-INDI/C-PAC/blob/2bec6713fdee9071d1b9852360b193f8fb5cbedb/CPAC/__init__.py#L29-L31 with https://github.com/FCP-INDI/C-PAC/blob/9884409e68b0e2aaa13e9eb903ca8e1d74aeb6ec/CPAC/__init__.py#L30-L33 and updates its calls …
=> 🐛 Remove local reliance on `${GITHUB_BRANCH}`

CPAC/resources/configs/pipeline_config_abcd-prep.yml, CPAC/resources/configs/pipeline_config_regtest-1.yml
Changes asked by @shnizzedy 
<details>
```
Version 1.1
Suite D4700
license and I have the right under that …
```
=> :package: reverting changes in config

CPAC/generate_motion_statistics/generate_motion_statistics.py, CPAC/nuisance/nuisance.py, CPAC/qc/xcp.py, CPAC/registration/registration.py
Fixes https://github.com/FCP-INDI/C-PAC/issues/2057#design-decisions-and-notes by @shnizzedy
Maybe fixes #1301 by @sgiavasis 
Maybe fixes #1308 by @cbin-cnl 
If we want some but not all of these, we can cherry-pick them into #2073 or revert the ones we don't want here before merging.
<details>
```
Version 1.1
Suite D4700 …
```
=> ⚡️ Throttle `calc_ants_warp`, `cal_DVARS` and all `cosine_filter`s

CHANGELOG.md, CPAC/generate_motion_statistics/generate_motion_statistics.py, CPAC/nuisance/nuisance.py, CPAC/pipeline/nipype_pipeline_engine/engine.py, CPAC/pipeline/nipype_pipeline_engine/plugins/cpac_nipype_custom.py, CPAC/pipeline/test/test_nipype_pipeline_engine.py, CPAC/qc/xcp.py, CPAC/registration/registration.py, CPAC/utils/typing.py
Fixes #2057 by @shnizzedy 
- Add `"throttle"` parameter to `Node`s, estimating all available memory when applied.
- Set `throttle=True` for `aCompCor_cosine_filter` Node.
- Test memory throttling with both multiproc plugins.
- #2081
https://github.com/FCP-INDI/C-PAC/blob/3e8c441dea149f0c4cab3aae7eceddff7b7b65df/CPAC/pipeline/test/test_nipype_pipeline_engine.py#L62-L85
<details>
```
Version 1.1
Suite D4700
By making a contribution to this …
```
=> ⚡️ Throttle `aCompCor_cosine_filter`

.pre-commit-config.yaml, .ruff.toml
<details>
```
Version 1.1
Suite D4700
license and I have the right under that license to submit that
work with …
```
=> Upgrade Ruff to 0.3.2

CPAC/pipeline/engine.py, CPAC/resources/configs/pipeline_config_default.yml, CPAC/resources/configs/pipeline_config_fmriprep-ingress.yml, CPAC/utils/datasource.py
Changes in this PR:
1. Value for `surface_connectivity` was `On` in the default pipeline config, so I changed it to `Off`
2. Made the Regressors dictionary optional when pulling regressors from fMRIPrep. Before, it crashed if there were no regressor strategies listed, but those aren't necessary for fmriprep ingress so they shouldn't be required
3. Removed most of the regressor list in the `fmriprep-ingress` config, since only bandpass filtering can be run with ingress
4. Made `echo-time2` optional, since sometimes `echo_time1` and `echo_time3` are populated but not `echo_time2`. There is already a check to make sure there are at least two echo times.
Ran full regression suite on these changes, and ran fmriprep-ingress and develop on the fMRIPrep ingress fix. 
<details>
<summary>Developer …
=> 🐞 Final bugfixes 1.8.7

CPAC/pipeline/engine.py, CPAC/pipeline/schema.py, dev/docker_data/run.py
Fixes #2086 by @nx10 
This PR makes FreeSurfer ingress possible from the command line without requiring a data config file. I added this feature to make the many_pipelines project run more smoothly so I will update the changelog if this makes it into `main`! 
This feature has been tested successfully on multiple subjects.
<details>
```
Version 1.1
Suite D4700
(a) The contribution was …
```
=> ✨Allow FS ingress from command line

CHANGELOG.md, CPAC/pipeline/engine.py
Fixes #2086 by @nx10 
This feature allows users to configure FreeSurfer ingress from the command line, so they no longer need to use a data config.
The engine can now accept FS directories from the data config file, but also can parse a FreeSurfer directory from the top level. 
`  --freesurfer_dir /data_dir/freesurfer`
This was tested locally and Florian ran test_config with this feature on many subjects. The user can specify the FS directory at the 
<details>
```
Version 1.1
Suite D4700
license document, but changing it is not …
```
=> :sparkles: Make fs ingress configurable from commandline

CPAC/func_preproc/func_preproc.py, CPAC/registration/registration.py, CPAC/surface/surf_preproc.py
Related to #2047 by @sgiavasis 
Related to one of [Florian issues](https://github.com/orgs/FCP-INDI/projects/8?pane=issue&itemId=50589024) 
- missing resource `space-template_res-bold_desc-brain_T1w`
This PR adds node to generate the missing resource `space-template_res-bold_desc-brain_T1w` if it is not found in the `rpool`, which is required for [transform_timeseries_to_T1template_abcd nodeblock](https://github.com/FCP-INDI/C-PAC/blob/013aaab4a80baa0f11b9ed24d1e54ce39a15f1ed/CPAC/registration/registration.py#L3779)
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute …
```
=> Fix missing resource `space-template_res-bold_desc-brain_T1w`

CPAC/qc/xcp.py
Fixes #2002 by @shnizzedy 
Merge after #2088 
When creating [C-PAC_pre-commit_examples](https://github.com/childmindresearch/C-PAC_pre-commit_examples) and [GH00011 Contributing to C-PAC: using pre-commit](https://docs.google.com/document/d/1WmKICJAMSIUlsFmUFgvbD-Ev9YmTQ9B9xPGbjVpxi8c), I found real small-scope changes to make. This PR represents the code portion of those changes, as illustrated in the "1: double-branching" row of the ["Comparison of options" table](https://github.com/childmindresearch/C-PAC_pre-commit_examples?tab=readme-ov-file#comparison-of-options).
<details>
```
Version 1.1
Suite D4700
San Francisco, …
```
=> 📝 Update XCP-QC docstring

CPAC/_entrypoints/run.py, CPAC/pipeline/engine.py
added few attributes and methods.
<details>
```
Version 1.1
Suite D4700
of my knowledge, is covered under an appropriate …
```
=> Introduced resource object in the rpool.

CPAC/pipeline/engine.py
<details>
```
Version 1.1
Suite D4700
license and I have the …
```
=> added sub- and ses- in the relative paths

CPAC/pipeline/engine.py
<details>
```
Version 1.1
Suite D4700
license and I have the …
```
=> only write .json files to .nii.gz image files

.github/workflows/smoke_test_participant.yml
Fixes 
```BASH
Package git-annex-standalone is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'git-annex-standalone' has no installation candidate
```
[in smoke tests](https://github.com/FCP-INDI/C-PAC/actions/runs/9782271352/job/27008515551)
Upgrades the `git-annex-standalone` install source from the Ubuntu 20.04 LTS (Focal Fossa) Neurodebian APT repo to the Ubuntu 22.04 LTS (Jammy Jellyfish) one in the smoke test CI workflow file.
[✅ Run participant smoke test #639](https://github.com/FCP-INDI/C-PAC/actions/runs/9783292036)
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> 👷⬆️ Upgrade `git-annex-standalone` for smoke tests

CPAC/utils/configuration/configuration.py
Related to <details><summary>https://github.com/FCP-INDI/C-PAC/issues/2145#issuecomment-2323253398 by @suxpert</summary>
> I regard the config file as `terrified` since it:
> […]
> - was too complex since there are too many things to write, but I did not find the logic of all those stuffs;
</details>
Related to <details><summary>https://github.com/FCP-INDI/C-PAC/issues/2145#issuecomment-2327403236 by @tamsinrogers</summary>
> If FROM is not specified, the pipeline will be based on [the blank pipeline](https://github.com/FCP-INDI/C-PAC/blob/v1.8.7/CPAC/resources/configs/pipeline_config_blank.yml).
</details>
Related to <details><summary>#1801 by @shnizzedy</summary>
> * Updates the base for minified configs from default to blank.
</details>
Related to …
=> 📝 Update `FROM` base from `default` to `blank`

.pre-commit-config.yaml, CHANGELOG.md, CPAC/pipeline/cpac_pipeline.py, README.md
Fixes 
* Skips https://github.com/FCP-INDI/C-PAC/blob/f92fde14ba5a6c37247903f70e84979a276ffb4a/.pre-commit-config.yaml#L26-L27 https://github.com/FCP-INDI/C-PAC/blob/f92fde14ba5a6c37247903f70e84979a276ffb4a/.pre-commit-config.yaml#L73-L83 when running pre-commit on `pre-commit.ci`
* Adds a [![pre-commit.ci status](https://results.pre-commit.ci/badge/github/FCP-INDI/C-PAC/main.svg)](https://results.pre-commit.ci/latest/github/FCP-INDI/C-PAC/main) badge to the README
We can't let it autofix ruff errors yet[^1]<sup>,</sup>[^2], and the requirements for `update-yaml-comments` are too large for pre-commit.ci, but we can let pre-commit.ci enforce the rest of the formatting rules.
[^1]: [🎨 Run pre-commit hooks on whole repo § Technical details. …
=> 👷 Skip `ruff` and `update-yaml-comments` for pre-config CI

CPAC/nuisance/utils/compcor.py, CPAC/resources/configs/pipeline_config_blank.yml
Fixes #2057 by @shnizzedy
Related to
- Optimizing aCompCor Cosine filter
- Mitigating "out-of -memory" crash during cosine filtering of long BOLD data.
The method is edited to use python generator approach and process one voxel timeseries at a time rather than loading the whole Bold matrix to the memory.
This implementation reduces the memory consumption by half (~16 GB max instead of  30 + GB)
For testing purpose, the output of this approach is compared with the original output using [correlation](https://github.com/birajstha/CPAC_regtest_pack/blob/main/corr_two_ts.py)
after update, the correlation test result are [here.](https://github.com/birajstha/acompcor_cosine_fiter_correlation_test/blob/main/correlation.txt)
<details>
``` …
```
=> ⚡️Optimize cosine filter

.github/dependabot.yaml
Related to #2187 by @shnizzedy, @birajstha & @dependabot
When I was writing #2187, I rediscovered [this stale branch](https://github.com/FCP-INDI/C-PAC/commits/c10c0f683828095f94e71e6b31e7aa35c98aa758/) that would have prevented this issue. This PR adds the Python Dependabot config from that branch on top of the GitHub Actions config from #2187.
<details>
```
Version 1.1
Suite D4700
(a) …
```
=> 👷 🔧 Configure Dependabot for Python dependencies

CHANGELOG.md, CPAC/anat_preproc/anat_preproc.py, CPAC/pipeline/engine.py, CPAC/pipeline/resource_inventory.py, CPAC/utils/outputs.py, setup.py
Related to #757 by @sgiavasis 
Related to https://github.com/FCP-INDI/fcp-indi.github.io/issues/185 by @sgiavasis 
Related to https://github.com/FCP-INDI/fcp-indi.github.io/issues/180 by @sgiavasis 
Crawls the codebase looking for where resources are
* created in the resource pool, either directly or as outputs from nodeblocks
* used as inputs for nodeblocks
* output to the output directory
and creates an inventory YAML file listing this information alphabetically.
* I based this PR on `many_pipes`, but it should be trivial to rebase it if we want it to go to `develop` or another branch instead.
* You should be able to run like
```BASH
docker run --rm -it --entrypoint resource_inventory ghcr.io/fcp-indi/c-pac:resource_inventory [-h] [-o [OUTPUT]]
```
to get an inventory like …
=> ✨ Inventory Resources

CPAC/func_preproc/func_preproc.py, CPAC/registration/registration.py
Typos in [here](https://github.com/FCP-INDI/C-PAC/blob/dc500a6b974e3efa634cfa4ffeffb827e83bc22a/CPAC/func_preproc/func_preproc.py#L1637) and [here](https://github.com/FCP-INDI/C-PAC/blob/dc500a6b974e3efa634cfa4ffeffb827e83bc22a/CPAC/registration/registration.py#L4408)
Fixing 
```python
wf.connect(
node,
out,
anat_brain_mask_to_func_res,
"inputspec.pace-template_desc-brain_mask",
)
```
with
```python
wf.connect(
node,
out,
anat_brain_mask_to_func_res,
"inputspec.space-template_desc-brain_mask",
)
```
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim copies …
```
=> fixing typos

CPAC/resources/configs/pipeline_config_blank.yml, CPAC/resources/configs/pipeline_config_default.yml
Related to Discussion [here](https://github.com/FCP-INDI/C-PAC/pull/2183#discussion_r2016868757) by @shnizzedy 
Related to #2183 
Lets not put TODOs in the user facing CONFIG files.
Reverting the TODOs added in blank and default configs on this PR #2183 
<details>
```
Version 1.1
Suite D4700
have the right to submit it …
```
=> removing TODO from config
